const chargersFigures = [
    // vehicles
    {
        figName: "Barrel Blaster",
        characterId: 155,
        elementId: 8,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        rare: true,
        value: 10.00,
    },
    {
        figName: "Burn Cycle",
        characterId: 10,
        elementId: 1,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        value: 1.00,
    },
    {
        figName: "Buzz Wing",
        characterId: 154,
        elementId: 8,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        rare: true,
        value: 10.00,
    },
    {
        figName: "Clown Cruiser",
        characterId: 147,
        elementId: 1,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        rare: true,
        value: 10.00,
    },
    {
        figName: "Crypt Crusher",
        characterId: 146,
        elementId: 7,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        value: 4.00,
    },
    {
        figName: "Dive Bomber",
        characterId: 145,
        elementId: 2,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        value: 3.00,
    },
    {
        figName: "Gold Rusher",
        characterId: 25,
        elementId: 3,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        rare: true,
        value: 15.00,
    },
    {
        figName: "Hot Streak",
        characterId: 151,
        elementId: 1,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        value: 5.00,
    },
    {
        figName: "Jet Stream",
        characterId: 46,
        elementId: 5,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        value: 3.00,
    },
    {
        figName: "Reef Ripper",
        characterId: 13,
        elementId: 2,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        value: 3.00,
    },
    {
        figName: "Sea Shadow",
        characterId: 149,
        elementId: 10,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        value: 3.00,
    },
    {
        figName: "Shark Tank",
        characterId: 24,
        elementId: 4,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        value: 3.00,
    },
    {
        figName: "Shield Striker",
        characterId: 148,
        elementId: 3,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        value: 1.00,
    },
    {
        figName: "Sky Slicer",
        characterId: 153,
        elementId: 5,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        value: 4.00,
    },
    {
        figName: "Soda Skimmer",
        characterId: 47,
        elementId: 6,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        value: 3.00,
    },
    {
        figName: "Splatter Splasher",
        characterId: 152,
        elementId: 6,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        value: 4.00,
    },
    {
        figName: "Stealth Stinger",
        characterId: 21,
        elementId: 8,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        value: 3.00,
    },
    {
        figName: "Sun Runner",
        characterId: 144,
        elementId: 9,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        rare: true,
        value: 8.00,
    },
    {
        figName: "Thump Truck",
        characterId: 150,
        elementId: 4,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        value: 3.00,
    },
    {
        figName: "Tomb Buggy",
        characterId: 81,
        elementId: 7,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        value: 4.00,
    },
    // chargers standard
    {
        figName: "Astroblast",
        characterId: 144,
        elementId: 9,
        gameId: 5,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 3.00,
    },
    {
        figName: "Hammer Slam Bowser",
        characterId: 147,
        elementId: 1,
        gameId: 5,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: true,
        value: 10.00,
    },
    {
        figName: "Dive Clops",
        characterId: 145,
        elementId: 2,
        gameId: 5,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 3.00,
    },
    {
        figName: "Donkey Kong",
        characterId: 155,
        elementId: 8,
        gameId: 5,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: true,
        value: 10.00,
    },
    {
        figName: "Lava Lance Eruptor",
        characterId: 10,
        elementId: 1,
        gameId: 5,
        type: "standard",
        variation: "series 4",
        img: "",
        value: 1.00,
    },
    {
        figName: "Fiesta",
        characterId: 146,
        elementId: 7,
        gameId: 5,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 6.00,
    },
    {
        figName: "Deep Dive Gill Grunt",
        characterId: 13,
        elementId: 2,
        gameId: 5,
        type: "standard",
        variation: "series 5",
        img: "",
        value: 2.00,
    },
    {
        figName: "High Volt",
        characterId: 148,
        elementId: 3,
        gameId: 5,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 1.00,
    },
    {
        figName: "Hurricane Jet Vac",
        characterId: 46,
        elementId: 5,
        gameId: 5,
        type: "standard",
        variation: "series 4",
        img: "",
        value: 1.00,
    },
    {
        figName: "Nightfall",
        characterId: 149,
        elementId: 10,
        gameId: 5,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 7.00,
    },
    {
        figName: "Big Bubble Pop Fizz",
        characterId: 47,
        elementId: 6,
        gameId: 5,
        type: "standard",
        variation: "series 4",
        img: "",
        value: 3.00,
    },
    {
        figName: "Bone Bash Roller Brawl",
        characterId: 81,
        elementId: 7,
        gameId: 5,
        type: "standard",
        variation: "series 2",
        img: "",
        rare: true,
        value: 10.00,
    },
    {
        figName: "Smash Hit",
        characterId: 150,
        elementId: 4,
        gameId: 5,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 1.00,
    },
    {
        figName: "Spitfire",
        characterId: 151,
        elementId: 1,
        gameId: 5,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 5.00,
    },
    {
        figName: "Splat",
        characterId: 152,
        elementId: 6,
        gameId: 5,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 3.00,
    },
    {
        figName: "Super Shot Stealth Elf",
        characterId: 21,
        elementId: 8,
        gameId: 5,
        type: "standard",
        variation: "series 4",
        img: "",
        value: 1.00,
    },
    {
        figName: "Stormblade",
        characterId: 153,
        elementId: 5,
        gameId: 5,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 4.00,
    },
    {
        figName: "Shark Shooter Terrafin",
        characterId: 24,
        elementId: 4,
        gameId: 5,
        type: "standard",
        variation: "series 4",
        img: "",
        value: 1.00,
    },
    {
        figName: "Thrillipede",
        characterId: 154,
        elementId: 8,
        gameId: 5,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: true,
        value: 8.00,
    },
    {
        figName: "Double Dare Trigger Happy",
        characterId: 25,
        elementId: 3,
        gameId: 5,
        type: "standard",
        variation: "series 4",
        img: "",
        rare: true,
        value: 30.00,
    },
    // variants
    {
        figName: "Birthday Bash Pop Fizz",
        characterId: 47,
        elementId: 6,
        gameId: 5,
        type: "standard",
        variation: "holiday",
        img: "",
        value: 6.00,
    },
    {
        figName: "Dark Hammer Slam Bowser",
        characterId: 147,
        elementId: 1,
        gameId: 5,
        type: "standard",
        variation: "dark",
        img: "",
        rare: true,
        value: 35.00,
    },
    {
        figName: "Dark Donkey Kong",
        characterId: 155,
        elementId: 8,
        gameId: 5,
        type: "standard",
        variation: "dark",
        img: "",
        rare: true,
        value: 25.00,
    },
    {
        figName: "Dark Spitfire",
        characterId: 151,
        elementId: 1,
        gameId: 5,
        type: "standard",
        variation: "dark",
        img: "",
        value: 8.00,
    },
    {
        figName: "Dark Super Shot Stealth Elf",
        characterId: 21,
        elementId: 8,
        gameId: 5,
        type: "standard",
        variation: "dark",
        img: "",
        value: 5.00,
    },
    {
        figName: "Eggcited Thrillipede",
        characterId: 154,
        elementId: 8,
        gameId: 5,
        type: "standard",
        variation: "holiday",
        img: "",
        value: 8.00,
    },
    {
        figName: "Frightful Fiesta",
        characterId: 146,
        elementId: 7,
        gameId: 5,
        type: "standard",
        variation: "holiday",
        img: "",
        value: 7.00,
    },
    {
        figName: "Legendary Astroblast",
        characterId: 144,
        elementId: 9,
        gameId: 5,
        type: "standard",
        variation: "legendary",
        img: "",
        value: 6.00,
    },
    {
        figName: "Legendary Bone Bash Roller Brawl",
        characterId: 81,
        elementId: 7,
        gameId: 5,
        type: "standard",
        variation: "legendary",
        img: "",
        rare: true,
        value: 12.00,
    },
    {
        figName: "Missile-Tow Dive Clops",
        characterId: 145,
        elementId: 2,
        gameId: 5,
        type: "standard",
        variation: "holiday",
        img: "",
        value: 6.00,
    },
    {
        figName: "Power Blue Splat",
        characterId: 152,
        elementId: 6,
        gameId: 5,
        type: "standard",
        variation: "blue",
        img: "",
        rare: true,
        value: 8.00,
    },
    {
        figName: "Power Blue Trigger Happy",
        characterId: 25,
        elementId: 3,
        gameId: 5,
        type: "standard",
        variation: "blue",
        img: "",
        rare: true,
        value: 25.00,
    },
    {
        figName: "Steel Plated Smash Hit",
        characterId: 150,
        elementId: 4,
        gameId: 5,
        type: "standard",
        variation: "metallic",
        img: "",
        value: 2.50,
    },
    {
        figName: "Bronze Bone Bash Roller Brawl",
        characterId: 81,
        elementId: 7,
        gameId: 5,
        type: "standard",
        variation: "metallic",
        img: "",
        rare: true,
        value: 100.00,
    },
    {
        figName: "Patina High Volt",
        characterId: 148,
        elementId: 3,
        gameId: 5,
        type: "standard",
        variation: "patina",
        img: "",
        rare: true,
        value: 15.00,
    },
    {
        figName: "Patina Lava Lance Eruptor",
        characterId: 10,
        elementId: 1,
        gameId: 5,
        type: "standard",
        variation: "patina",
        img: "",
        rare: true,
        value: 200.00,
    },
    {
        figName: "Snow-Brite Stormblade",
        characterId: 153,
        elementId: 5,
        gameId: 5,
        type: "standard",
        variation: "jade",
        img: "",
        rare: true,
        value: 50.00,
    },
    // vehicle variants
    {
        figName: "Dark Barrel Blaster",
        characterId: 155,
        elementId: 8,
        gameId: 5,
        type: "vehicle",
        variation: "dark",
        img: "",
        value: 1.00,
    },
    {
        figName: "Dark Clown Cruiser",
        characterId: 147,
        elementId: 1,
        gameId: 5,
        type: "vehicle",
        variation: "dark",
        img: "",
        value: 6.00,
    },
    {
        figName: "Dark Hot Streak",
        characterId: 151,
        elementId: 1,
        gameId: 5,
        type: "vehicle",
        variation: "dark",
        img: "",
        value: 3.00,
    },
    {
        figName: "Dark Sea Shadow",
        characterId: 149,
        elementId: 10,
        gameId: 5,
        type: "vehicle",
        variation: "dark",
        img: "",
        value: 6.00,
    },
    {
        figName: "E3 Hot Streak",
        characterId: 151,
        elementId: 1,
        gameId: 5,
        type: "vehicle",
        variation: "event",
        img: "",
        rare: true,
        value: 14.00,
    },
    {
        figName: "Golden Hot Streak",
        characterId: 151,
        elementId: 1,
        gameId: 5,
        type: "vehicle",
        variation: "metallic",
        img: "",
        rare: true,
        value: 20.00,
    },
    {
        figName: "Legendary Sun Runner",
        characterId: 144,
        elementId: 9,
        gameId: 5,
        type: "vehicle",
        variation: "legendary",
        img: "",
        value: 1.00,
    },
    {
        figName: "Nitro Soda Skimmer",
        characterId: 47,
        elementId: 6,
        gameId: 5,
        type: "vehicle",
        variation: "nitro",
        img: "",
        value: 6.00,
    },
    {
        figName: "Nitro Stealth Stinger",
        characterId: 21,
        elementId: 8,
        gameId: 5,
        type: "vehicle",
        variation: "nitro",
        img: "",
        value: 3.00,
    },
    {
        figName: "Power Blue Gold Rusher",
        characterId: 25,
        elementId: 3,
        gameId: 5,
        type: "vehicle",
        variation: "blue",
        img: "",
        rare: true,
        value: 25.00,
    },
    {
        figName: "Power Blue Splatter Splasher",
        characterId: 152,
        elementId: 6,
        gameId: 5,
        type: "vehicle",
        variation: "blue",
        img: "",
        rare: true,
        value: 20.00,
    },
    {
        figName: "Spring Ahead Dive Bomber",
        characterId: 145,
        elementId: 2,
        gameId: 5,
        type: "vehicle",
        variation: "holiday",
        img: "",
        value: 6.00,
    },
    {
        figName: "Bronze Tomb Buggy",
        characterId: 81,
        elementId: 7,
        gameId: 5,
        type: "vehicle",
        variation: "metallic",
        img: "",
        rare: true,
        value: 100.00,
    },
    {
        figName: "Patina Burn Cycle",
        characterId: 10,
        elementId: 1,
        gameId: 5,
        type: "vehicle",
        variation: "patina",
        img: "",
        rare: true,
        value: 30.00,
    },
    {
        figName: "Patina Shield Striker",
        characterId: 148,
        elementId: 3,
        gameId: 5,
        type: "vehicle",
        variation: "patina",
        img: "",
        rare: true,
        value: 65.00,
    },
];

module.exports = chargersFigures;