const chargersFigures = [
    // vehicles
    {
        figName: "Barrel Blaster",
        characterId: 155,
        elementId: 8,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        rare: true,
        value: 1000,
    },
    {
        figName: "Burn Cycle",
        characterId: 10,
        elementId: 1,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        value: 100,
    },
    {
        figName: "Buzz Wing",
        characterId: 154,
        elementId: 8,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        rare: true,
        value: 1000,
    },
    {
        figName: "Clown Cruiser",
        characterId: 147,
        elementId: 1,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        rare: true,
        value: 1000,
    },
    {
        figName: "Crypt Crusher",
        characterId: 146,
        elementId: 7,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        value: 400,
    },
    {
        figName: "Dive Bomber",
        characterId: 145,
        elementId: 2,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        value: 300,
    },
    {
        figName: "Gold Rusher",
        characterId: 25,
        elementId: 3,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        rare: true,
        value: 1500,
    },
    {
        figName: "Hot Streak",
        characterId: 151,
        elementId: 1,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        value: 500,
    },
    {
        figName: "Jet Stream",
        characterId: 46,
        elementId: 5,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        value: 300,
    },
    {
        figName: "Reef Ripper",
        characterId: 13,
        elementId: 2,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        value: 300,
    },
    {
        figName: "Sea Shadow",
        characterId: 149,
        elementId: 10,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        value: 300,
    },
    {
        figName: "Shark Tank",
        characterId: 24,
        elementId: 4,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        value: 300,
    },
    {
        figName: "Shield Striker",
        characterId: 148,
        elementId: 3,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        value: 100,
    },
    {
        figName: "Sky Slicer",
        characterId: 153,
        elementId: 5,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        value: 400,
    },
    {
        figName: "Soda Skimmer",
        characterId: 47,
        elementId: 6,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        value: 300,
    },
    {
        figName: "Splatter Splasher",
        characterId: 152,
        elementId: 6,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        value: 400,
    },
    {
        figName: "Stealth Stinger",
        characterId: 21,
        elementId: 8,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        value: 300,
    },
    {
        figName: "Sun Runner",
        characterId: 144,
        elementId: 9,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        rare: true,
        value: 800,
    },
    {
        figName: "Thump Truck",
        characterId: 150,
        elementId: 4,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        value: 300,
    },
    {
        figName: "Tomb Buggy",
        characterId: 81,
        elementId: 7,
        gameId: 5,
        type: "vehicle",
        variation: "series 1",
        img: "",
        value: 400,
    },
    // chargers standard
    {
        figName: "Astroblast",
        characterId: 144,
        elementId: 9,
        gameId: 5,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 300,
    },
    {
        figName: "Hammer Slam Bowser",
        characterId: 147,
        elementId: 1,
        gameId: 5,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: true,
        value: 1000,
    },
    {
        figName: "Dive Clops",
        characterId: 145,
        elementId: 2,
        gameId: 5,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 300,
    },
    {
        figName: "Donkey Kong",
        characterId: 155,
        elementId: 8,
        gameId: 5,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: true,
        value: 1000,
    },
    {
        figName: "Lava Lance Eruptor",
        characterId: 10,
        elementId: 1,
        gameId: 5,
        type: "standard",
        variation: "series 4",
        img: "",
        value: 100,
    },
    {
        figName: "Fiesta",
        characterId: 146,
        elementId: 7,
        gameId: 5,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 600,
    },
    {
        figName: "Deep Dive Gill Grunt",
        characterId: 13,
        elementId: 2,
        gameId: 5,
        type: "standard",
        variation: "series 5",
        img: "",
        value: 200,
    },
    {
        figName: "High Volt",
        characterId: 148,
        elementId: 3,
        gameId: 5,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 100,
    },
    {
        figName: "Hurricane Jet Vac",
        characterId: 46,
        elementId: 5,
        gameId: 5,
        type: "standard",
        variation: "series 4",
        img: "",
        value: 100,
    },
    {
        figName: "Nightfall",
        characterId: 149,
        elementId: 10,
        gameId: 5,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 700,
    },
    {
        figName: "Big Bubble Pop Fizz",
        characterId: 47,
        elementId: 6,
        gameId: 5,
        type: "standard",
        variation: "series 4",
        img: "",
        value: 300,
    },
    {
        figName: "Bone Bash Roller Brawl",
        characterId: 81,
        elementId: 7,
        gameId: 5,
        type: "standard",
        variation: "series 2",
        img: "",
        rare: true,
        value: 1000,
    },
    {
        figName: "Smash Hit",
        characterId: 150,
        elementId: 4,
        gameId: 5,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 100,
    },
    {
        figName: "Spitfire",
        characterId: 151,
        elementId: 1,
        gameId: 5,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 500,
    },
    {
        figName: "Splat",
        characterId: 152,
        elementId: 6,
        gameId: 5,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 300,
    },
    {
        figName: "Super Shot Stealth Elf",
        characterId: 21,
        elementId: 8,
        gameId: 5,
        type: "standard",
        variation: "series 4",
        img: "",
        value: 100,
    },
    {
        figName: "Stormblade",
        characterId: 153,
        elementId: 5,
        gameId: 5,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 400,
    },
    {
        figName: "Shark Shooter Terrafin",
        characterId: 24,
        elementId: 4,
        gameId: 5,
        type: "standard",
        variation: "series 4",
        img: "",
        value: 100,
    },
    {
        figName: "Thrillipede",
        characterId: 154,
        elementId: 8,
        gameId: 5,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: true,
        value: 800,
    },
    {
        figName: "Double Dare Trigger Happy",
        characterId: 25,
        elementId: 3,
        gameId: 5,
        type: "standard",
        variation: "series 4",
        img: "",
        rare: true,
        value: 3000,
    },
    // variants
    {
        figName: "Birthday Bash Pop Fizz",
        characterId: 47,
        elementId: 6,
        gameId: 5,
        type: "standard",
        variation: "holiday",
        img: "",
        value: 600,
    },
    {
        figName: "Dark Hammer Slam Bowser",
        characterId: 147,
        elementId: 1,
        gameId: 5,
        type: "standard",
        variation: "dark",
        img: "",
        rare: true,
        value: 3500,
    },
    {
        figName: "Dark Donkey Kong",
        characterId: 155,
        elementId: 8,
        gameId: 5,
        type: "standard",
        variation: "dark",
        img: "",
        rare: true,
        value: 2500,
    },
    {
        figName: "Dark Spitfire",
        characterId: 151,
        elementId: 1,
        gameId: 5,
        type: "standard",
        variation: "dark",
        img: "",
        value: 800,
    },
    {
        figName: "Dark Super Shot Stealth Elf",
        characterId: 21,
        elementId: 8,
        gameId: 5,
        type: "standard",
        variation: "dark",
        img: "",
        value: 500,
    },
    {
        figName: "Eggcited Thrillipede",
        characterId: 154,
        elementId: 8,
        gameId: 5,
        type: "standard",
        variation: "holiday",
        img: "",
        value: 800,
    },
    {
        figName: "Frightful Fiesta",
        characterId: 146,
        elementId: 7,
        gameId: 5,
        type: "standard",
        variation: "holiday",
        img: "",
        value: 700,
    },
    {
        figName: "Legendary Astroblast",
        characterId: 144,
        elementId: 9,
        gameId: 5,
        type: "standard",
        variation: "legendary",
        img: "",
        value: 600,
    },
    {
        figName: "Legendary Bone Bash Roller Brawl",
        characterId: 81,
        elementId: 7,
        gameId: 5,
        type: "standard",
        variation: "legendary",
        img: "",
        rare: true,
        value: 1200,
    },
    {
        figName: "Missile-Tow Dive Clops",
        characterId: 145,
        elementId: 2,
        gameId: 5,
        type: "standard",
        variation: "holiday",
        img: "",
        value: 600,
    },
    {
        figName: "Power Blue Splat",
        characterId: 152,
        elementId: 6,
        gameId: 5,
        type: "standard",
        variation: "blue",
        img: "",
        rare: true,
        value: 800,
    },
    {
        figName: "Power Blue Trigger Happy",
        characterId: 25,
        elementId: 3,
        gameId: 5,
        type: "standard",
        variation: "blue",
        img: "",
        rare: true,
        value: 2500,
    },
    {
        figName: "Steel Plated Smash Hit",
        characterId: 150,
        elementId: 4,
        gameId: 5,
        type: "standard",
        variation: "metallic",
        img: "",
        value: 250,
    },
    {
        figName: "Bronze Bone Bash Roller Brawl",
        characterId: 81,
        elementId: 7,
        gameId: 5,
        type: "standard",
        variation: "metallic",
        img: "",
        rare: true,
        value: 10000,
    },
    {
        figName: "Patina High Volt",
        characterId: 148,
        elementId: 3,
        gameId: 5,
        type: "standard",
        variation: "patina",
        img: "",
        rare: true,
        value: 1500,
    },
    {
        figName: "Patina Lava Lance Eruptor",
        characterId: 10,
        elementId: 1,
        gameId: 5,
        type: "standard",
        variation: "patina",
        img: "",
        rare: true,
        value: 20000,
    },
    {
        figName: "Snow-Brite Stormblade",
        characterId: 153,
        elementId: 5,
        gameId: 5,
        type: "standard",
        variation: "jade",
        img: "",
        rare: true,
        value: 5000,
    },
    // vehicle variants
    {
        figName: "Dark Barrel Blaster",
        characterId: 155,
        elementId: 8,
        gameId: 5,
        type: "vehicle",
        variation: "dark",
        img: "",
        value: 100,
    },
    {
        figName: "Dark Clown Cruiser",
        characterId: 147,
        elementId: 1,
        gameId: 5,
        type: "vehicle",
        variation: "dark",
        img: "",
        value: 600,
    },
    {
        figName: "Dark Hot Streak",
        characterId: 151,
        elementId: 1,
        gameId: 5,
        type: "vehicle",
        variation: "dark",
        img: "",
        value: 300,
    },
    {
        figName: "Dark Sea Shadow",
        characterId: 149,
        elementId: 10,
        gameId: 5,
        type: "vehicle",
        variation: "dark",
        img: "",
        value: 600,
    },
    {
        figName: "E3 Hot Streak",
        characterId: 151,
        elementId: 1,
        gameId: 5,
        type: "vehicle",
        variation: "event",
        img: "",
        rare: true,
        value: 1400,
    },
    {
        figName: "Golden Hot Streak",
        characterId: 151,
        elementId: 1,
        gameId: 5,
        type: "vehicle",
        variation: "metallic",
        img: "",
        rare: true,
        value: 2000,
    },
    {
        figName: "Legendary Sun Runner",
        characterId: 144,
        elementId: 9,
        gameId: 5,
        type: "vehicle",
        variation: "legendary",
        img: "",
        value: 100,
    },
    {
        figName: "Nitro Soda Skimmer",
        characterId: 47,
        elementId: 6,
        gameId: 5,
        type: "vehicle",
        variation: "nitro",
        img: "",
        value: 600,
    },
    {
        figName: "Nitro Stealth Stinger",
        characterId: 21,
        elementId: 8,
        gameId: 5,
        type: "vehicle",
        variation: "nitro",
        img: "",
        value: 300,
    },
    {
        figName: "Power Blue Gold Rusher",
        characterId: 25,
        elementId: 3,
        gameId: 5,
        type: "vehicle",
        variation: "blue",
        img: "",
        rare: true,
        value: 2500,
    },
    {
        figName: "Power Blue Splatter Splasher",
        characterId: 152,
        elementId: 6,
        gameId: 5,
        type: "vehicle",
        variation: "blue",
        img: "",
        rare: true,
        value: 2000,
    },
    {
        figName: "Spring Ahead Dive Bomber",
        characterId: 145,
        elementId: 2,
        gameId: 5,
        type: "vehicle",
        variation: "holiday",
        img: "",
        value: 600,
    },
    {
        figName: "Bronze Tomb Buggy",
        characterId: 81,
        elementId: 7,
        gameId: 5,
        type: "vehicle",
        variation: "metallic",
        img: "",
        rare: true,
        value: 10000,
    },
    {
        figName: "Patina Burn Cycle",
        characterId: 10,
        elementId: 1,
        gameId: 5,
        type: "vehicle",
        variation: "patina",
        img: "",
        rare: true,
        value: 3000,
    },
    {
        figName: "Patina Shield Striker",
        characterId: 148,
        elementId: 3,
        gameId: 5,
        type: "vehicle",
        variation: "patina",
        img: "",
        rare: true,
        value: 6500,
    },
    // Eon's Elite Chargers
    {
        figName: "Elite Boomer",
        characterId: 2,
        elementId: 3,
        gameId: 5,
        type: "standard",
        variation: "elite",
        img: "",
        rare: true,
        value: 1000,
    },
    {
        figName: "Elite Dino-Rang",
        characterId: 6,
        elementId: 4,
        gameId: 5,
        type: "standard",
        variation: "elite",
        img: "",
        rare: true,
        value: 1200,
    },
    {
        figName: "Elite Ghost Roaster",
        characterId: 12,
        elementId: 4,
        gameId: 5,
        type: "standard",
        variation: "elite",
        img: "",
        rare: true,
        value: 1500,
    },
    {
        figName: "Elite Slam Bam",
        characterId: 18,
        elementId: 2,
        gameId: 5,
        type: "standard",
        variation: "elite",
        img: "",
        rare: true,
        value: 1500,
    },
    {
        figName: "Elite Voodood",
        characterId: 26,
        elementId: 6,
        gameId: 5,
        type: "standard",
        variation: "elite",
        img: "",
        rare: true,
        value: 1000,
    },
    {
        figName: "Elite Zook",
        characterId: 32,
        elementId: 8,
        gameId: 5,
        type: "standard",
        variation: "elite",
        img: "",
        rare: true,
        value: 1000,
    },
];

module.exports = chargersFigures;