const giantsFigures = [
    // giants
    {
        figName: "Bouncer",
        characterId: 37,
        elementId: 3,
        gameId: 2,
        type: "giant",
        variation: "series 1",
        img: "",
        value: 1.50,
    },
    {
        figName: "Crusher",
        characterId: 38,
        elementId: 4,
        gameId: 2,
        type: "giant",
        variation: "series 1",
        img: "",
        value: 1.50,
    },
    {
        figName: "Tree Rex",
        characterId: 39,
        elementId: 8,
        gameId: 2,
        type: "giant",
        variation: "series 1",
        img: "",
        value: 1.50,
    },
    {
        figName: "Hot Head",
        characterId: 40,
        elementId: 1,
        gameId: 2,
        type: "giant",
        variation: "series 1",
        img: "",
        value: 1.50,
    },
    {
        figName: "Swarm",
        characterId: 41,
        elementId: 5,
        gameId: 2,
        type: "giant",
        variation: "series 1",
        img: "",
        value: 1.50,
    },
    {
        figName: "Eye Brawl",
        characterId: 42,
        elementId: 7,
        gameId: 2,
        type: "giant",
        variation: "series 1",
        img: "",
        value: 1.50,
    },
    {
        figName: "Thumpback",
        characterId: 43,
        elementId: 2,
        gameId: 2,
        type: "giant",
        variation: "series 1",
        img: "",
        value: 1.50,
    },
    {
        figName: "Ninjini",
        characterId: 44,
        elementId: 6,
        gameId: 2,
        type: "giant",
        variation: "series 1",
        img: "",
        value: 1.50,
    },
    // giants standard
    {
        figName: "Bash S-2",
        characterId: 1,
        elementId: 4,
        gameId: 2,
        type: "standard",
        variation: "series 2",
        img: "",
        value: 1.50,
    },
    {
        figName: "Chill",
        characterId: 50,
        elementId: 2,
        gameId: 2,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 1.50,
    },
    {
        figName: "LightCore Chill",
        characterId: 50,
        elementId: 2,
        gameId: 2,
        type: "standard",
        variation: "lightcore",
        img: "",
        value: 1.50,
    },
    {
        figName: "Chop Chop S-2",
        characterId: 4,
        elementId: 7,
        gameId: 2,
        type: "standard",
        variation: "series 2",
        img: "",
        value: 1.50,
    },
    {
        figName: "Cynder S-2",
        characterId: 5,
        elementId: 7,
        gameId: 2,
        type: "standard",
        variation: "series 2",
        img: "",
        value: 1.50,
    },
    {
        figName: "Double Trouble S-2",
        characterId: 7,
        elementId: 6,
        gameId: 2,
        type: "standard",
        variation: "series 2",
        img: "",
        value: 1.50,
    },
    {
        figName: "Drobot S-2",
        characterId: 9,
        elementId: 3,
        gameId: 2,
        type: "standard",
        variation: "series 2",
        img: "",
        value: 1.50,
    },
    {
        figName: "LightCore Drobot",
        characterId: 9,
        elementId: 3,
        gameId: 2,
        type: "standard",
        variation: "lightcore",
        img: "",
        value: 1.50,
    },
    {
        figName: "Eruptor S-2",
        characterId: 10,
        elementId: 1,
        gameId: 2,
        type: "standard",
        variation: "series 2",
        img: "",
        value: 1.50,
    },
    {
        figName: "LightCore Eruptor",
        characterId: 10,
        elementId: 1,
        gameId: 2,
        type: "standard",
        variation: "lightcore",
        img: "",
        value: 1.50,
    },
    {
        figName: "Flameslinger S-2",
        characterId: 11,
        elementId: 1,
        gameId: 2,
        type: "standard",
        variation: "series 2",
        img: "",
        value: 1.50,
    },
    {
        figName: "Flashwing",
        characterId: 49,
        elementId: 4,
        gameId: 2,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 1.50,
    },
    {
        figName: "Fright Rider",
        characterId: 48,
        elementId: 7,
        gameId: 2,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 1.50,
    },
    {
        figName: "Gill Grunt S-2",
        characterId: 13,
        elementId: 2,
        gameId: 2,
        type: "standard",
        variation: "series 2",
        img: "",
        value: 1.50,
    },
    {
        figName: "Hex S-2",
        characterId: 14,
        elementId: 7,
        gameId: 2,
        type: "standard",
        variation: "series 2",
        img: "",
        value: 1.50,
    },
    {
        figName: "LightCore Hex",
        characterId: 14,
        elementId: 7,
        gameId: 2,
        type: "standard",
        variation: "lightcore",
        img: "",
        value: 1.50,
    },
    {
        figName: "Hot Dog",
        characterId: 52,
        elementId: 1,
        gameId: 2,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 1.50,
    },
    {
        figName: "Ignitor S-2",
        characterId: 15,
        elementId: 1,
        gameId: 2,
        type: "standard",
        variation: "series 2",
        img: "",
        value: 1.50,
    },
    {
        figName: "Jet-Vac",
        characterId: 46,
        elementId: 5,
        gameId: 2,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 1.50,
    },
    {
        figName: "LightCore Jet-Vac",
        characterId: 46,
        elementId: 5,
        gameId: 2,
        type: "standard",
        variation: "lightcore",
        img: "",
        value: 1.50,
    },
    {
        figName: "Lightning Rod S-2",
        characterId: 16,
        elementId: 5,
        gameId: 2,
        type: "standard",
        variation: "series 2",
        img: "",
        value: 1.50,
    },
    {
        figName: "Pop Fizz",
        characterId: 47,
        elementId: 6,
        gameId: 2,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 1.50,
    },
    {
        figName: "LightCore Pop Fizz",
        characterId: 47,
        elementId: 6,
        gameId: 2,
        type: "standard",
        variation: "lightcore",
        img: "",
        value: 1.50,
    },
    {
        figName: "Prism Break",
        characterId: 17,
        elementId: 4,
        gameId: 2,
        type: "standard",
        variation: "series 2",
        img: "",
        value: 1.50,
    },
    {
        figName: "LightCore Prism Break",
        characterId: 17,
        elementId: 4,
        gameId: 2,
        type: "standard",
        variation: "lightcore",
        img: "",
        value: 1.50,
    },
    {
        figName: "Shroom Boom",
        characterId: 45,
        elementId: 8,
        gameId: 2,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 1.50,
    },
    {
        figName: "LightCore Shroom Boom",
        characterId: 45,
        elementId: 8,
        gameId: 2,
        type: "standard",
        variation: "lightcore",
        img: "",
        value: 1.50,
    },
    {
        figName: "Slam Bam S-2",
        characterId: 18,
        elementId: 2,
        gameId: 2,
        type: "standard",
        variation: "series 2",
        img: "",
        value: 1.50,
    },
    {
        figName: "Sonic Boom",
        characterId: 19,
        elementId: 5,
        gameId: 2,
        type: "standard",
        variation: "series 2",
        img: "",
        value: 1.50,
    },
    {
        figName: "Sprocket",
        characterId: 51,
        elementId: 3,
        gameId: 2,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 1.50,
    },
    {
        figName: "Spyro S-2",
        characterId: 20,
        elementId: 6,
        gameId: 2,
        type: "standard",
        variation: "series 2",
        img: "",
        value: 1.50,
    },
    {
        figName: "Stealth Elf S-2",
        characterId: 21,
        elementId: 8,
        gameId: 2,
        type: "standard",
        variation: "series 2",
        img: "",
        value: 1.50,
    },
    {
        figName: "Stump Smash S-2",
        characterId: 22,
        elementId: 8,
        gameId: 2,
        type: "standard",
        variation: "series 2",
        img: "",
        value: 1.50,
    },
    {
        figName: "Terrafin S-2",
        characterId: 24,
        elementId: 4,
        gameId: 2,
        type: "standard",
        variation: "series 2",
        img: "",
        value: 1.50,
    },
    {
        figName: "Trigger Happy S-2",
        characterId: 25,
        elementId: 3,
        gameId: 2,
        type: "standard",
        variation: "series 2",
        img: "",
        value: 1.50,
    },
    {
        figName: "Whirlwind S-2",
        characterId: 29,
        elementId: 5,
        gameId: 2,
        type: "standard",
        variation: "series 2",
        img: "",
        value: 1.50,
    },
    {
        figName: "Wrecking Ball S-2",
        characterId: 30,
        elementId: 6,
        gameId: 2,
        type: "standard",
        variation: "series 2",
        img: "",
        value: 1.50,
    },
    {
        figName: "Zap S-2",
        characterId: 31,
        elementId: 2,
        gameId: 2,
        type: "standard",
        variation: "series 2",
        img: "",
        value: 1.50,
    },
    {
        figName: "Zook S-2",
        characterId: 32,
        elementId: 8,
        gameId: 2,
        type: "standard",
        variation: "series 2",
        img: "",
        value: 1.50,
    },
    // Giants sidekicks
    {
        figName: "Barkley",
        characterId: 53,
        elementId: 8,
        gameId: 2,
        type: "sidekick",
        variation: "series 1",
        img: "",
        value: 1.50,
    },
    {
        figName: "Eye Small",
        characterId: 54,
        elementId: 7,
        gameId: 2,
        type: "sidekick",
        variation: "series 1",
        img: "",
        value: 1.50,
    },
    {
        figName: "Mini Jini",
        characterId: 55,
        elementId: 6,
        gameId: 2,
        type: "sidekick",
        variation: "series 1",
        img: "",
        value: 1.50,
    },
    {
        figName: "Thumpling",
        characterId: 56,
        elementId: 2,
        gameId: 2,
        type: "sidekick",
        variation: "series 1",
        img: "",
        value: 1.50,
    },
    // Giants variants
    {
        figName: "",
        characterId: ,
        elementId: ,
        gameId: 2,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 1.50,
    },
];

module.exports = giantsFigures;