const imaginatorsFigures = [
    // senseis
    {
        figName: "Air Strike",
        characterId: 156,
        elementId: 5,
        gameId: 6,
        setId: 15,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 15.00,
    },
    {
        figName: "Ambush",
        characterId: 157,
        elementId: 8,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 10.00,
    },
    {
        figName: "Aurora",
        characterId: 158,
        elementId: 9,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 10.00,
    },
    {
        figName: "Barbella",
        characterId: 159,
        elementId: 4,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 7.00,
    },
    {
        figName: "Boom Bloom",
        characterId: 160,
        elementId: 8,
        gameId: 6,
        setId: 16,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 20.00,
    },
    {
        figName: "Buckshot",
        characterId: 161,
        elementId: 6,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 20.00,
    },
    {
        figName: "Chain Reaction",
        characterId: 162,
        elementId: 3,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 25.00,
    },
    {
        figName: "Chopscotch",
        characterId: 163,
        elementId: 7,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 9.00,
    },
    {
        figName: "Crash Bandicoot",
        characterId: 164,
        elementId: 8,
        gameId: 6,
        setId: 17,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 12.00,
    },
    {
        figName: "Dr. Neo Cortex",
        characterId: 165,
        elementId: 3,
        gameId: 6,
        setId: 17,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 9.00,
    },
    {
        figName: "Ember",
        characterId: 166,
        elementId: 1,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 12.00,
    },
    {
        figName: "Flarewolf",
        characterId: 167,
        elementId: 1,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 20.00,
    },
    {
        figName: "King Pen",
        characterId: 168,
        elementId: 2,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 1.00,
    },
    {
        figName: "Mysticat",
        characterId: 169,
        elementId: 6,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 13.00,
    },
    {
        figName: "Pit Boss",
        characterId: 170,
        elementId: 7,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 18.00,
    },
    {
        figName: "Ro-Bow",
        characterId: 171,
        elementId: 3,
        gameId: 6,
        setId: 19,
        type: "sensei",
        variation: "series 1",
        img: "",
        rare: true,
        value: 100.00,
    },
    {
        figName: "Starcast",
        characterId: 172,
        elementId: 10,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 28.00,
    },
    {
        figName: "Tidepool",
        characterId: 173,
        elementId: 2,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 15.00,
    },
    {
        figName: "Tri-Tip",
        characterId: 174,
        elementId: 4,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 6.00,
    },
    {
        figName: "Wild Storm",
        characterId: 175,
        elementId: 5,
        gameId: 6,
        setId: 18,
        type: "sensei",
        variation: "series 1",
        img: "",
        rare: true,
        value: 100.00,
    },
    {
        figName: "Bad Juju",
        characterId: 176,
        elementId: 5,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 15.00,
    },
    {
        figName: "Blaster-Tron",
        characterId: 177,
        elementId: 3,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 25.00,
    },
    {
        figName: "Chompy Mage",
        characterId: 178,
        elementId: 8,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 20.00,
    },
    {
        figName: "Dr. Krankcase",
        characterId: 179,
        elementId: 3,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 15.00,
    },
    {
        figName: "Golden Queen",
        characterId: 180,
        elementId: 4,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 3.00,
    },
    {
        figName: "Grave Clobber",
        characterId: 181,
        elementId: 2,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 15.00,
    },
    {
        figName: "Hood Sickle",
        characterId: 182,
        elementId: 10,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 30.00,
    },
    {
        figName: "Kaos",
        characterId: 183,
        elementId: 10,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 35.00,
    },
    {
        figName: "Pain-Yatta",
        characterId: 184,
        elementId: 6,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 25.00,
    },
    {
        figName: "Tae Kwon Crow",
        characterId: 185,
        elementId: 1,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 12.00,
    },
    {
        figName: "Wolfgang",
        characterId: 186,
        elementId: 7,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 20.00,
    },
    // creation crystals
    {
        figName: "Air Angel",
        characterId: 187,
        elementId: 5,
        gameId: 6,
        type: "crystal",
        variation: "series 1",
        img: "",
        value: 10.00,
    },
    {
        figName: "Air Lantern",
        characterId: 187,
        elementId: 5,
        gameId: 6,
        setId: 16,
        type: "crystal",
        variation: "series 1",
        img: "",
        value: 10.00,
    },
    {
        figName: "Dark Pyramid",
        characterId: 188,
        elementId: 10,
        gameId: 6,
        type: "crystal",
        variation: "series 1",
        img: "",
        rare: true,
        value: 25.00,
    },
    {
        figName: "Dark Reactor",
        characterId: 188,
        elementId: 10,
        gameId: 6,
        type: "crystal",
        variation: "series 1",
        img: "",
        rare: true,
        value: 25.00,
    },
    {
        figName: "Dark Rune",
        characterId: 188,
        elementId: 10,
        gameId: 6,
        type: "crystal",
        variation: "series 1",
        img: "",
        rare: true,
        value: 25.00,
    },
    {
        figName: "Earth Armor",
        characterId: 189,
        elementId: 4,
        gameId: 6,
        setId: 15,
        type: "crystal",
        variation: "series 1",
        img: "",
        value: 10.00,
    },
    {
        figName: "Earth Rocket",
        characterId: 189,
        elementId: 4,
        gameId: 6,
        type: "crystal",
        variation: "series 1",
        img: "",
        value: 10.00,
    },
    {
        figName: "Fire Acorn",
        characterId: 190,
        elementId: 1,
        gameId: 6,
        type: "crystal",
        variation: "series 1",
        img: "",
        value: 10.00,
    },
    {
        figName: "Fire Reactor",
        characterId: 190,
        elementId: 1,
        gameId: 6,
        type: "crystal",
        variation: "series 1",
        img: "",
        value: 5.00,
    },
    {
        figName: "Life Acorn",
        characterId: 191,
        elementId: 8,
        gameId: 6,
        type: "crystal",
        variation: "series 1",
        img: "",
        value: 10.00,
    },
    {
        figName: "Life Claw",
        characterId: 191,
        elementId: 8,
        gameId: 6,
        setId: 18,
        type: "crystal",
        variation: "series 1",
        img: "",
        value: 10.00,
    },
    {
        figName: "Life Rocket",
        characterId: 191,
        elementId: 8,
        gameId: 6,
        type: "crystal",
        variation: "series 1",
        img: "",
        value: 10.00,
    },
    {
        figName: "Life Rune",
        characterId: 191,
        elementId: 8,
        gameId: 6,
        type: "crystal",
        variation: "series 1",
        img: "",
        value: 10.00,
    },
    {
        figName: "Light Fanged",
        characterId: 192,
        elementId: 9,
        gameId: 6,
        type: "crystal",
        variation: "series 1",
        img: "",
        value: 13.00,
    },
    {
        figName: "Light Rune",
        characterId: 192,
        elementId: 9,
        gameId: 6,
        type: "crystal",
        variation: "series 1",
        img: "",
        value: 13.00,
    },
    {
        figName: "Magic Claw",
        characterId: 193,
        elementId: 6,
        gameId: 6,
        type: "crystal",
        variation: "series 1",
        img: "",
        rare: true,
        value: 30.00,
    },
    {
        figName: "Magic Lantern",
        characterId: 193,
        elementId: 6,
        gameId: 6,
        setId: 19,
        type: "crystal",
        variation: "series 1",
        img: "",
        value: 10.00,
    },
    {
        figName: "Magic Pyramid",
        characterId: 193,
        elementId: 6,
        gameId: 6,
        type: "crystal",
        variation: "series 1",
        img: "",
        value: 10.00,
    },
    {
        figName: "Tech Armor",
        characterId: 194,
        elementId: 3,
        gameId: 6,
        type: "crystal",
        variation: "series 1",
        img: "",
        value: 10.00,
    },
    {
        figName: "Tech Reactor",
        characterId: 194,
        elementId: 3,
        gameId: 6,
        type: "crystal",
        variation: "series 1",
        img: "",
        value: 10.00,
    },
    {
        figName: "Undead Claw",
        characterId: 195,
        elementId: 7,
        gameId: 6,
        type: "crystal",
        variation: "series 1",
        img: "",
        value: 10.00,
    },
    {
        figName: "Undead Fanged",
        characterId: 195,
        elementId: 7,
        gameId: 6,
        type: "crystal",
        variation: "series 1",
        img: "",
        value: 10.00,
    },
    {
        figName: "Undead Lantern",
        characterId: 195,
        elementId: 7,
        gameId: 6,
        type: "crystal",
        variation: "series 1",
        img: "",
        value: 10.00,
    },
    {
        figName: "Water Armor",
        characterId: 196,
        elementId: 2,
        gameId: 6,
        type: "crystal",
        variation: "series 1",
        img: "",
        value: 10.00,
    },
    {
        figName: "Water Fanged",
        characterId: 196,
        elementId: 2,
        gameId: 6,
        type: "crystal",
        variation: "series 1",
        img: "",
        value: 10.00,
    },
    {
        figName: "Water Rocket",
        characterId: 196,
        elementId: 2,
        gameId: 6,
        type: "crystal",
        variation: "series 1",
        img: "",
        value: 10.00,
    },
    // variants
    {
        figName: "Candy-Coated Chopscotch",
        characterId: 163,
        elementId: 7,
        gameId: 6,
        type: "sensei",
        variation: "holiday",
        img: "",
        value: 12.00,
    },
    {
        figName: "Dark King Pen",
        characterId: 168,
        elementId: 2,
        gameId: 6,
        type: "sensei",
        variation: "dark",
        img: "",
        value: 10.00,
    },
    {
        figName: "Egg Bomber Air Strike",
        characterId: 156,
        elementId: 5,
        gameId: 6,
        type: "sensei",
        variation: "holiday",
        img: "",
        value: 15.00,
    },
    {
        figName: "Hard-Boiled Flarewolf",
        characterId: 167,
        elementId: 1,
        gameId: 6,
        type: "sensei",
        variation: "holiday",
        img: "",
        value: 25.00,
    },
    {
        figName: "Legendary Pit Boss",
        characterId: 170,
        elementId: 7,
        gameId: 6,
        type: "sensei",
        variation: "legendary",
        img: "",
        value: 18.00,
    },
    {
        figName: "Legendary Tri-Tip",
        characterId: 174,
        elementId: 4,
        gameId: 6,
        type: "sensei",
        variation: "legendary",
        img: "",
        value: 12.00,
    },
    {
        figName: "Solar Flare Aurora",
        characterId: 158,
        elementId: 9,
        gameId: 6,
        type: "sensei",
        variation: "dark",
        img: "",
        value: 14.00,
    },
    {
        figName: "Clear Starcast",
        characterId: 172,
        elementId: 10,
        gameId: 6,
        type: "sensei",
        variation: "clear",
        img: "",
        rare: true,
        value: 150.00,
    },
    {
        figName: "Dec-Ember",
        characterId: 166,
        elementId: 1,
        gameId: 6,
        type: "sensei",
        variation: "holiday",
        img: "",
        rare: true,
        value: 65.00,
    },
    {
        figName: "Orange Chain Reaction",
        characterId: 162,
        elementId: 3,
        gameId: 6,
        type: "sensei",
        variation: "orange",
        img: "",
        rare: true, 
        value: 30.00,
    },
    {
        figName: "Pink Barbella",
        characterId: 159,
        elementId: 4,
        gameId: 6,
        type: "sensei",
        variation: "pink",
        img: "",
        rare: true, 
        value: 190.00,
    },
    {
        figName: "Dark Golden Queen",
        characterId: 180,
        elementId: 4,
        gameId: 6,
        type: "sensei",
        variation: "dark",
        img: "",
        value: 16.00,
    },
    {
        figName: "Dark Wolfgang",
        characterId: 186,
        elementId: 7,
        gameId: 6,
        type: "sensei",
        variation: "dark",
        img: "",
        value: 20.00,
    },
    {
        figName: "Jingle Bell Chompy Mage",
        characterId: 178,
        elementId: 8,
        gameId: 6,
        type: "sensei",
        variation: "holiday",
        img: "",
        value: 25.00,
    },
    {
        figName: "Mystical Bad Juju",
        characterId: 176,
        elementId: 5,
        gameId: 6,
        type: "sensei",
        variation: "dark",
        img: "",
        value: 22.00,
    },
    {
        figName: "Mystical Tae Kwon Crow",
        characterId: 185,
        elementId: 1,
        gameId: 6,
        type: "sensei",
        variation: "dark",
        img: "",
        value: 18.00,
    },
    {
        figName: "Steel Plated Hood Sickle",
        characterId: 182,
        elementId: 10,
        gameId: 6,
        type: "sensei",
        variation: "metallic",
        img: "",
        rare: true,
        value: 40.00,
    },
    {
        figName: "Rock Candy Pain-Yatta",
        characterId: 184,
        elementId: 6,
        gameId: 6,
        type: "sensei",
        variation: "blue",
        img: "",
        rare: true,
        value: 50.00,
    },
    {
        figName: "Legendary Life Acorn",
        characterId: 191,
        elementId: 8,
        gameId: 6,
        type: "crystal",
        variation: "legendary",
        img: "",
        value: 18.00,
    },
    {
        figName: "Legendary Light Fanged",
        characterId: 192,
        elementId: 9,
        gameId: 6,
        type: "crystal",
        variation: "legendary",
        img: "",
        value: 18.00,
    },
    {
        figName: "Legendary Magic Lantern",
        characterId: 193,
        elementId: 6,
        gameId: 6,
        type: "crystal",
        variation: "legendary",
        img: "",
        value: 18.00,
    },
];

module.exports = imaginatorsFigures;