const imaginatorsFigures = [
    // senseis
    {
        figName: "Air Strike",
        characterId: 200,
        elementId: 5,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 15.00,
    },
    {
        figName: "Ambush",
        characterId: 201,
        elementId: 8,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 10.00,
    },
    {
        figName: "Aurora",
        characterId: 202,
        elementId: 9,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 10.00,
    },
    {
        figName: "Barbella",
        characterId: 203,
        elementId: 4,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 7.00,
    },
    {
        figName: "Boom Bloom",
        characterId: 204,
        elementId: 8,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 20.00,
    },
    {
        figName: "Buckshot",
        characterId: 205,
        elementId: 6,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 20.00,
    },
    {
        figName: "Chain Reaction",
        characterId: 206,
        elementId: 3,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 25.00,
    },
    {
        figName: "Chopscotch",
        characterId: 207,
        elementId: 7,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 9.00,
    },
    {
        figName: "Crash Bandicoot",
        characterId: 208,
        elementId: 8,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 12.00,
    },
    {
        figName: "Dr. Neo Cortex",
        characterId: 209,
        elementId: 3,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 9.00,
    },
    {
        figName: "Ember",
        characterId: 210,
        elementId: 1,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 12.00,
    },
    {
        figName: "Flarewolf",
        characterId: 211,
        elementId: 1,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 20.00,
    },
    {
        figName: "King Pen",
        characterId: 212,
        elementId: 2,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 1.00,
    },
    {
        figName: "Mysticat",
        characterId: 213,
        elementId: 6,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 13.00,
    },
    {
        figName: "Pit Boss",
        characterId: 214,
        elementId: 7,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 18.00,
    },
    {
        figName: "Ro-Bow",
        characterId: 215,
        elementId: 3,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        rare: true,
        value: 100.00,
    },
    {
        figName: "Starcast",
        characterId: 216,
        elementId: 10,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 28.00,
    },
    {
        figName: "Tidepool",
        characterId: 217,
        elementId: 2,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 15.00,
    },
    {
        figName: "Tri-Tip",
        characterId: 218,
        elementId: 4,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        value: 6.00,
    },
    {
        figName: "Wild Storm",
        characterId: 219,
        elementId: 5,
        gameId: 6,
        type: "sensei",
        variation: "series 1",
        img: "",
        rare: true,
        value: 100.00,
    },
];

module.exports = imaginatorsFigures;