const spyrosFigures = [
    // spyro's standard
    {
        figName: "Bash",
        characterId: 1,
        elementId: 4,
        gameId: 1,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: false,
        value: 150,
        stock: 1,
        damaged: 0,
    },
    {
        figName: "Boomer",
        characterId: 2,
        elementId: 3,
        gameId: 1,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: false,
        value: 500,
        stock: 1,
        damaged: 0,
    },
    {
        figName: "Camo",
        characterId: 3,
        elementId: 8,
        gameId: 1,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: false,
        value: 150,
        stock: 1,
        damaged: 0,
    },
    {
        figName: "Chop Chop",
        characterId: 4,
        elementId: 7,
        gameId: 1,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: false,
        value: 150,
        stock: 1,
        damaged: 0,
    },
    {
        figName: "Cynder",
        characterId: 5,
        elementId: 7,
        gameId: 1,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: false,
        value: 150,
        stock: 1,
        damaged: 0,
    },
    {
        figName: "Dino-Rang",
        characterId: 6,
        elementId: 4,
        gameId: 1,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: false,
        value: 500,
        stock: 1,
        damaged: 0,
    },
    {
        figName: "Double Trouble",
        characterId: 7,
        elementId: 6,
        gameId: 1,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: false,
        value: 150,
        stock: 1,
        damaged: 0,
    },
    {
        figName: "Drill Sergeant",
        characterId: 8,
        elementId: 3,
        gameId: 1,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: false,
        value: 150,
        stock: 1,
        damaged: 0,
    },
    {
        figName: "Drobot",
        characterId: 9,
        elementId: 3,
        gameId: 1,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: false,
        value: 150,
        stock: 1,
        damaged: 0,
    },
    {
        figName: "Eruptor",
        characterId: 10,
        elementId: 1,
        gameId: 1,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: false,
        value: 150,
        stock: 1,
        damaged: 0,
    },
    {
        figName: "Flameslinger",
        characterId: 11,
        elementId: 1,
        gameId: 1,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: false,
        value: 150,
        stock: 1,
        damaged: 0,
    },
    {
        figName: "Ghost Roaster",
        characterId: 12,
        elementId: 7,
        gameId: 1,
        setId: 1,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: false,
        value: 500,
        stock: 1,
        damaged: 0,
    },
    {
        figName: "Gill Grunt",
        characterId: 13,
        elementId: 2,
        gameId: 1,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: false,
        value: 150,
        stock: 1,
        damaged: 0,
    },
    {
        figName: "Hex",
        characterId: 14,
        elementId: 7,
        gameId: 1,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: false,
        value: 150,
        stock: 1,
        damaged: 0,
    },
    {
        figName: "Ignitor",
        characterId: 15,
        elementId: 1,
        gameId: 1,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: false,
        value: 150,
        stock: 1,
        damaged: 0,
    },
    {
        figName: "Lightning Rod",
        characterId: 16,
        elementId: 5,
        gameId: 1,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: false,
        value: 150,
        stock: 1,
        damaged: 0,
    },
    {
        figName: "Prism Break",
        characterId: 17,
        elementId: 4,
        gameId: 1,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: false,
        value: 150,
        stock: 1,
        damaged: 0,
    },
    {
        figName: "Slam Bam",
        characterId: 18,
        elementId: 2,
        gameId: 1,
        setId: 3,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: false,
        value: 500,
        stock: 1,
        damaged: 0,
    },
    {
        figName: "Sonic Boom",
        characterId: 19,
        elementId: 5,
        gameId: 1,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: false,
        value: 150,
        stock: 1,
        damaged: 0,
    },
    {
        figName: "Spyro",
        characterId: 20,
        elementId: 6,
        gameId: 1,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: false,
        value: 150,
        stock: 1,
        damaged: 0,
    },
    {
        figName: "Stealth Elf",
        characterId: 21,
        elementId: 8,
        gameId: 1,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: false,
        value: 150,
        stock: 1,
        damaged: 0,
    },
    {
        figName: "Stump Smash",
        characterId: 22,
        elementId: 8,
        gameId: 1,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: false,
        value: 150,
        stock: 1,
        damaged: 0,
    },
    {
        figName: "Sunburn",
        characterId: 23,
        elementId: 1,
        gameId: 1,
        setId: 2,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: false,
        value: 500,
        stock: 1,
        damaged: 0,
    },
    {
        figName: "Terrafin",
        characterId: 24,
        elementId: 4,
        gameId: 1,
        setId: 4,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: false,
        value: 150,
        stock: 1,
        damaged: 0,
    },
    {
        figName: "Trigger Happy",
        characterId: 25,
        elementId: 3,
        gameId: 1,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: false,
        value: 150,
        stock: 1,
        damaged: 0,
    },
    {
        figName: "Voodood",
        characterId: 26,
        elementId: 6,
        gameId: 1,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: false,
        value: 500,
        stock: 1,
        damaged: 0,
    },
    {
        figName: "Warnado",
        characterId: 27,
        elementId: 5,
        gameId: 1,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: false,
        value: 500,
        stock: 1,
        damaged: 0,
    },
    {
        figName: "Wham Shell",
        characterId: 28,
        elementId: 2,
        gameId: 1,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: false,
        value: 1200,
        stock: 1,
        damaged: 0,
    },
    {
        figName: "Whirlwind",
        characterId: 29,
        elementId: 5,
        gameId: 1,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: false,
        value: 150,
        stock: 1,
        damaged: 0,
    },
    {
        figName: "Wrecking Ball",
        characterId: 30,
        elementId: 6,
        gameId: 1,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: false,
        value: 500,
        stock: 1,
        damaged: 0,
    },
    {
        figName: "Zap",
        characterId: 31,
        elementId: 2,
        gameId: 1,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: false,
        value: 5,
        stock: 1,
        damaged: 0,
    },
    {
        figName: "Zook",
        characterId: 32,
        elementId: 8,
        gameId: 1,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: false,
        value: 150,
        stock: 1,
        damaged: 0,
    },
    // spyro's sidekicks
    {
        figName: "Gill Runt",
        characterId: 33,
        elementId: 2,
        gameId: 1,
        type: "sidekick",
        variation: "series 1",
        img: "",
        rare: false,
        value: 400,
        stock: 1,
        damaged: 0,
    },
    {
        figName: "Terrabite",
        characterId: 34,
        elementId: 4,
        gameId: 1,
        type: "sidekick",
        variation: "series 1",
        img: "",
        rare: false,
        value: 400,
        stock: 1,
        damaged: 0,
    },
    {
        figName: "Trigger Snappy",
        characterId: 35,
        elementId: 3,
        gameId: 1,
        type: "sidekick",
        variation: "series 1",
        img: "",
        rare: false,
        value: 400,
        stock: 1,
        damaged: 0,
    },
    {
        figName: "Whisper Elf",
        characterId: 36,
        elementId: 8,
        gameId: 1,
        type: "sidekick",
        variation: "series 1",
        img: "",
        rare: true,
        value: 1500,
        stock: 1,
        damaged: 0,
    },
    // spyro's variants
    {
        figName: "Dark Spyro",
        characterId: 20,
        elementId: 6,
        gameId: 1,
        type: "standard",
        variation: "dark",
        img: "",
        rare: true,
        value: 1000,
        stock: 0,
        damaged: 0,  
    },
    {
        figName: "Legendary Bash",
        characterId: 1,
        elementId: 4,
        gameId: 1,
        type: "standard",
        variation: "legendary",
        img: "",
        rare: false,
        value: 500,
        stock: 1,
        damaged: 0,  
    },
    {
        figName: "Legendary Chop Chop",
        characterId: 4,
        elementId: 7,
        gameId: 1,
        type: "standard",
        variation: "legendary",
        img: "",
        rare: true,
        value: 900,
        stock: 0,
        damaged: 0,  
    },
    {
        figName: "Legendary Spyro",
        characterId: 20,
        elementId: 6,
        gameId: 1,
        type: "standard",
        variation: "legendary",
        img: "",
        rare: true,
        value: 900,
        stock: 1,
        damaged: 0,  
    },
    {
        figName: "Legendary Trigger Happy",
        characterId: 25,
        elementId: 3,
        gameId: 1,
        type: "standard",
        variation: "legendary",
        img: "",
        rare: false,
        value: 500,
        stock: 1,
        damaged: 0,  
    },
    {
        figName: "Blue Bash",
        characterId: 1,
        elementId: 4,
        gameId: 1,
        type: "standard",
        variation: "blue",
        img: "",
        rare: true,
        value: 2000,
        stock: 0,
        damaged: 0,  
    },
    {
        figName: "Chrome Spyro",
        characterId: 20,
        elementId: 6,
        gameId: 1,
        type: "standard",
        variation: "chrome",
        img: "",
        rare: true,
        value: 20000,
        stock: 0,
        damaged: 0,  
    },
    {
        figName: "Crystal Clear Cynder",
        characterId: 5,
        elementId: 7,
        gameId: 1,
        type: "standard",
        variation: "clear",
        img: "",
        rare: true,
        value: 9000,
        stock: 0,
        damaged: 0,  
    },
    {
        figName: "Crystal Clear Stealth Elf",
        characterId: 21,
        elementId: 8,
        gameId: 1,
        type: "standard",
        variation: "clear",
        img: "",
        rare: true,
        value: 9000,
        stock: 0,
        damaged: 0,  
    },
    {
        figName: "Crystal Clear Wham Shell",
        characterId: 28,
        elementId: 2,
        gameId: 1,
        type: "standard",
        variation: "clear",
        img: "",
        rare: true,
        value: 9000,
        stock: 0,
        damaged: 0,  
    },
    {
        figName: "Crystal Clear Whirlwind",
        characterId: 29,
        elementId: 5,
        gameId: 1,
        type: "standard",
        variation: "clear",
        img: "",
        rare: true,
        value: 9000,
        stock: 0,
        damaged: 0,  
    },
    {
        figName: "Flocked Stump Smash",
        characterId: 22,
        elementId: 8,
        gameId: 1,
        type: "standard",
        variation: "flocked",
        img: "",
        rare: true,
        value: 3500,
        stock: 0,
        damaged: 0,  
    },
    {
        figName: "Glow-in-the-Dark Warnado",
        characterId: 27,
        elementId: 5,
        gameId: 1,
        type: "standard",
        variation: "glow",
        img: "",
        rare: true,
        value: 8000,
        stock: 0,
        damaged: 0,  
    },
    {
        figName: "Glow-in-the-Dark Wrecking Ball",
        characterId: 30,
        elementId: 6,
        gameId: 1,
        type: "standard",
        variation: "glow",
        img: "",
        rare: true,
        value: 15000,
        stock: 0,
        damaged: 0,  
    },
    {
        figName: "Glow-in-the-Dark Zap",
        characterId: 31,
        elementId: 2,
        gameId: 1,
        type: "standard",
        variation: "glow",
        img: "",
        rare: true,
        value: 7000,
        stock: 0,
        damaged: 0,  
    },
    {
        figName: "Gold Chop Chop",
        characterId: 4,
        elementId: 7,
        gameId: 1,
        type: "standard",
        variation: "gold",
        img: "",
        rare: true,
        value: 12000,
        stock: 0,
        damaged: 0,  
    },
    {
        figName: "Gold Drill Sergeant",
        characterId: 8,
        elementId: 3,
        gameId: 1,
        type: "standard",
        variation: "gold",
        img: "",
        rare: true,
        value: 7500,
        stock: 0,
        damaged: 0,  
    },
    {
        figName: "Gold Flameslinger",
        characterId: 11,
        elementId: 1,
        gameId: 1,
        type: "standard",
        variation: "gold",
        img: "",
        rare: true,
        value: 10000,
        stock: 0,
        damaged: 0,  
    },
    {
        figName: "Green Gill Grunt",
        characterId: 13,
        elementId: 2,
        gameId: 1,
        type: "standard",
        variation: "green",
        img: "",
        rare: true,
        value: 300,
        stock: 0,
        damaged: 0,  
    },
    {
        figName: "Metallic Purple Cynder",
        characterId: 5,
        elementId: 7,
        gameId: 1,
        type: "standard",
        variation: "metallic",
        img: "",
        rare: true,
        value: 8000,
        stock: 0,
        damaged: 0,  
    },
    {
        figName: "Pearl Hex",
        characterId: 14,
        elementId: 7,
        gameId: 1,
        type: "standard",
        variation: "pearl",
        img: "",
        rare: true,
        value: 10000,
        stock: 0,
        damaged: 0,  
    },
    {
        figName: "Red Camo",
        characterId: 3,
        elementId: 8,
        gameId: 1,
        type: "standard",
        variation: "red",
        img: "",
        rare: true,
        value: 30000,
        stock: 0,
        damaged: 0,  
    },
    {
        figName: "Red Drill Sergeant",
        characterId: 8,
        elementId: 3,
        gameId: 1,
        type: "standard",
        variation: "red",
        img: "",
        rare: false,
        value: 500,
        stock: 0,
        damaged: 0,  
    },
    {
        figName: "Silver Boomer",
        characterId: 2,
        elementId: 3,
        gameId: 1,
        type: "standard",
        variation: "silver",
        img: "",
        rare: true,
        value: 8000,
        stock: 0,
        damaged: 0,  
    },
    {
        figName: "Silver Dino-Rang",
        characterId: 6,
        elementId: 4,
        gameId: 1,
        type: "standard",
        variation: "silver",
        img: "",
        rare: true,
        value: 10000,
        stock: 0,
        damaged: 0,  
    },
    {
        figName: "Silver Eruptor",
        characterId: 10,
        elementId: 1,
        gameId: 1,
        type: "standard",
        variation: "silver",
        img: "",
        rare: true,
        value: 8000,
        stock: 0,
        damaged: 0,  
    },
];

module.exports = spyrosFigures;