const swapFigures = [
    // swap force
    {
        figName: "Hoot Loop",
        characterId: 57,
        elementId: 6,
        gameId: 3,
        type: "swap",
        variation: "series 1",
        img: "",
        value: 4.00,
    },
    {
        figName: "Trap Shadow",
        characterId: 58,
        elementId: 6,
        gameId: 3,
        type: "swap",
        variation: "series 1",
        img: "",
        value: 6.00,
    },
    {
        figName: "Magna Charge",
        characterId: 59,
        elementId: 3,
        gameId: 3,
        type: "swap",
        variation: "series 1",
        img: "",
        value: 9.00,
    },
    {
        figName: "Spy Rise",
        characterId: 60,
        elementId: 3,
        gameId: 3,
        type: "swap",
        variation: "series 1",
        img: "",
        value: 6.50,
    },
    {
        figName: "Wash Buckler",
        characterId: 61,
        elementId: 2,
        gameId: 3,
        type: "swap",
        variation: "series 1",
        img: "",
        value: 3.00,
    },
    {
        figName: "Freeze Blade",
        characterId: 62,
        elementId: 2,
        gameId: 3,
        type: "swap",
        variation: "series 1",
        img: "",
        value: 5.50,
    },
    {
        figName: "Blast Zone",
        characterId: 63,
        elementId: 1,
        gameId: 3,
        type: "swap",
        variation: "series 1",
        img: "",
        value: 2.00,
    },
    {
        figName: "Fire Kraken",
        characterId: 64,
        elementId: 1,
        gameId: 3,
        type: "swap",
        variation: "series 1",
        img: "",
        value: 5.00,
    },
    {
        figName: "Night Shift",
        characterId: 65,
        elementId: 7,
        gameId: 3,
        type: "swap",
        variation: "series 1",
        img: "",
        value: 5.50,
    },
    {
        figName: "Rattle Shake",
        characterId: 66,
        elementId: 7,
        gameId: 3,
        type: "swap",
        variation: "series 1",
        img: "",
        value: 7.00,
    },
    {
        figName: "Stink Bomb",
        characterId: 67,
        elementId: 8,
        gameId: 3,
        type: "swap",
        variation: "series 1",
        img: "",
        value: 7.00,
    },
    {
        figName: "Grilla Drilla",
        characterId: 68,
        elementId: 8,
        gameId: 3,
        type: "swap",
        variation: "series 1",
        img: "",
        value: 6.00,
    },
    {
        figName: "Free Ranger",
        characterId: 69,
        elementId: 5,
        gameId: 3,
        type: "swap",
        variation: "series 1",
        img: "",
        value: 5.00,
    },
    {
        figName: "Boom Jet",
        characterId: 70,
        elementId: 5,
        gameId: 3,
        type: "swap",
        variation: "series 1",
        img: "",
        value: 4.00,
    },
    {
        figName: "Rubble Rouser",
        characterId: 71,
        elementId: 4,
        gameId: 3,
        type: "swap",
        variation: "series 1",
        img: "",
        value: 5.50,
    },
    {
        figName: "Doom Stone",
        characterId: 72,
        elementId: 4,
        gameId: 3,
        type: "swap",
        variation: "series 1",
        img: "",
        rare: true,
        value: 30.00,
    },
    // standard sf figures
    {
        figName: "Bumble Blast",
        characterId: 73,
        elementId: 8,
        gameId: 3,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 2.50,
    },
    {
        figName: "LightCore Bumble Blast",
        characterId: 73,
        elementId:8 ,
        gameId: 3,
        type: "standard",
        variation: "lightcore",
        img: "",
        rare: true,
        value: 7.00,
    },
    {
        figName: "Camo S-2",
        characterId: 3,
        elementId: 8,
        gameId: 3,
        type: "standard",
        variation: "series 2",
        img: "",
        value: 6.00,
    },
    {
        figName: "Chill S-2",
        characterId: 50,
        elementId: 2,
        gameId: 3,
        type: "standard",
        variation: "series 2",
        img: "",
        value: 2.50,
    },
    {
        figName: "Chop Chop S-3",
        characterId: 4,
        elementId: 7,
        gameId: 3,
        type: "standard",
        variation: "series 3",
        img: "",
        value: 0.50,
    },
    {
        figName: "Countdown",
        characterId: 74,
        elementId: 3,
        gameId: 3,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 2.50,
    },
    {
        figName: "LightCore Countdown",
        characterId: 74,
        elementId: 3,
        gameId: 3,
        type: "standard",
        variation: "lightcore",
        img: "",
        value: 2.50,
    },
    {
        figName: "Cynder S-3",
        characterId: 5,
        elementId: 7,
        gameId: 3,
        type: "standard",
        variation: "series 3",
        img: "",
        value: 1.00,
    },
    {
        figName: "Dune Bug",
        characterId: 75,
        elementId: 6,
        gameId: 3,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 0.50,
    },
    {
        figName: "Eruptor S-3",
        characterId: 10,
        elementId: 1,
        gameId: 3,
        type: "standard",
        variation: "series 3",
        img: "",
        value: 1.00,
    },
    {
        figName: "LightCore Flashwing",
        characterId: 49,
        elementId: 4,
        gameId: 3,
        type: "standard",
        variation: "lightcore",
        img: "",
        value: 5.00,
    },
    {
        figName: "Fryno",
        characterId: 76,
        elementId: 1,
        gameId: 3,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 1.50,
    },
    {
        figName: "Gill Grunt S-3",
        characterId: 13,
        elementId: 2,
        gameId: 3,
        type: "standard",
        variation: "series 3",
        img: "",
        value: 2.50,
    },
    {
        figName: "Grim Creeper",
        characterId: 77,
        elementId: 7,
        gameId: 3,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 4.50,
    },
    {
        figName: "LightCore Grim Creeper",
        characterId: 77,
        elementId: 7,
        gameId: 3,
        type: "standard",
        variation: "lightcore",
        img: "",
        value: 2.50,
    },
    {
        figName: "Hot Dog S-2",
        characterId: 52,
        elementId: 1,
        gameId: 3,
        type: "standard",
        variation: "series 2",
        img: "",
        rare: true,
        value: 7.00,
    },
    {
        figName: "Jet-Vac S-2",
        characterId: 46,
        elementId: 5,
        gameId: 3,
        type: "standard",
        variation: "series 2",
        img: "",
        rare: true,
        value: 8.00,
    },
    {
        figName: "Pop Fizz S-2",
        characterId: 47,
        elementId: 6,
        gameId: 3,
        type: "standard",
        variation: "series 2",
        img: "",
        value: 3.50,
    },
    {
        figName: "Pop Thorn",
        characterId: 78,
        elementId: 5,
        gameId: 3,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 3.00,
    },
    {
        figName: "Prism Break S-3",
        characterId: 17,
        elementId: 4,
        gameId: 3,
        type: "standard",
        variation: "series 3",
        img: "",
        value: 2.00,
    },
    {
        figName: "Punk Shock",
        characterId: 79,
        elementId: 2,
        gameId: 3,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 9.00,
    },
    {
        figName: "Rip Tide",
        characterId: 80,
        elementId: 2,
        gameId: 3,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 3.50,
    },
    {
        figName: "Roller Brawl",
        characterId: 81,
        elementId: 7,
        gameId: 3,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 4.50,
    },
    {
        figName: "Scorp",
        characterId: 82,
        elementId: 4,
        gameId: 3,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 2.50,
    },
    {
        figName: "Scratch",
        characterId: 83,
        elementId: 5,
        gameId: 3,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: true,
        value: 20.00,
    },
    {
        figName: "Slobber Tooth",
        characterId: 84,
        elementId: 4,
        gameId: 3,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 3.00,
    },
    {
        figName: "Smolderdash",
        characterId: 85,
        elementId: 1,
        gameId: 3,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 3.00,
    },
    {
        figName: "LightCore Smolderdash",
        characterId: 85,
        elementId: 1,
        gameId: 3,
        type: "standard",
        variation: "lightcore",
        img: "",
        value: 1.50,
    },
    {
        figName: "Sprocket S-2",
        characterId: 51,
        elementId: 3,
        gameId: 3,
        type: "standard",
        variation: "series 2",
        img: "",
        value: 3.50,
    },
    {
        figName: "Spyro S-3",
        characterId: 20,
        elementId: 6,
        gameId: 3,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 0.50,
    },
    {
        figName: "Star Strike",
        characterId: 86,
        elementId: 6,
        gameId: 3,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 4.00,
    },
    {
        figName: "LightCore Star Strike",
        characterId: 86,
        elementId: 6,
        gameId: 3,
        type: "standard",
        variation: "lightcore",
        img: "",
        value: 1.00,
    },
    {
        figName: "Stealth Elf S-3",
        characterId: 21,
        elementId: 8,
        gameId: 3,
        type: "standard",
        variation: "series 3",
        img: "",
        value: 1.00,
    },
    {
        figName: "Terrafin S-3",
        characterId: 24,
        elementId: 4,
        gameId: 3,
        type: "standard",
        variation: "series 3",
        img: "",
        value: 1.00,
    },
    {
        figName: "Trigger Happy S-3",
        characterId: 25,
        elementId: 3,
        gameId: 3,
        type: "standard",
        variation: "series 3",
        img: "",
        value: 1.50,
    },
    {
        figName: "LightCore Warnado",
        characterId: 27,
        elementId: 5,
        gameId: 3,
        type: "standard",
        variation: "lightcore",
        img: "",
        value: 0.50,
    },
    {
        figName: "LightCore Wham Shell",
        characterId: 28,
        elementId: 2,
        gameId: 3,
        type: "standard",
        variation: "lightcore",
        img: "",
        value: 0.50,
    },
    {
        figName: "Whirlwind S-3",
        characterId: 29,
        elementId: 5,
        gameId: 3,
        type: "standard",
        variation: "series 3",
        img: "",
        value: 1.00,
    },
    {
        figName: "Wind Up",
        characterId: 87,
        elementId: 3,
        gameId: 3,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 4.00,
    },
    {
        figName: "Zoo Lou",
        characterId: 88,
        elementId: 8,
        gameId: 3,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 2.00,
    },
    // swap variants
];

module.exports = swapFigures;