const trapFigures = [
    // trap masters
    {
        figName: "Blastermind",
        characterId: 89,
        elementId: 6,
        gameId: 4,
        type: "master",
        variation: "series 1",
        img: "",
        value: 600,
    },
    {
        figName: "Bushwhack",
        characterId: 90,
        elementId: 8,
        gameId: 4,
        type: "master",
        variation: "series 1",
        img: "",
        value: 400,
    },
    {
        figName: "Enigma",
        characterId: 91,
        elementId: 6,
        gameId: 4,
        type: "master",
        variation: "series 1",
        img: "",
        value: 1500,
    },
    {
        figName: "Gearshift",
        characterId: 92,
        elementId: 3,
        gameId: 4,
        type: "master",
        variation: "series 1",
        img: "",
        value: 1000,
    },
    {
        figName: "Gusto",
        characterId: 93,
        elementId: 5,
        gameId: 4,
        type: "master",
        variation: "series 1",
        img: "",
        value: 300,
    },
    {
        figName: "Head Rush",
        characterId: 94,
        elementId: 4,
        gameId: 4,
        type: "master",
        variation: "series 1",
        img: "",
        value: 500,
    },
    {
        figName: "Jawbreaker",
        characterId: 95,
        elementId: 3,
        gameId: 4,
        type: "master",
        variation: "series 1",
        img: "",
        value: 500,
    },
    {
        figName: "Ka-Boom",
        characterId: 96,
        elementId: 1,
        gameId: 4,
        type: "master",
        variation: "series 1",
        img: "",
        value: 700,
    },
    {
        figName: "Knight Light",
        characterId: 97,
        elementId: 9,
        gameId: 4,
        setId: 14,
        type: "master",
        variation: "series 1",
        img: "",
        value: 2000,
    },
    {
        figName: "Knight Mare",
        characterId: 98,
        elementId: 10,
        gameId: 4,
        setId: 13,
        type: "master",
        variation: "series 1",
        img: "",
        value: 3000,
    },
    {
        figName: "Krypt King",
        characterId: 99,
        elementId: 7,
        gameId: 4,
        type: "master",
        variation: "series 1",
        img: "",
        value: 1000,
    },
    {
        figName: "Lob-Star",
        characterId: 100,
        elementId: 2,
        gameId: 4,
        type: "master",
        variation: "series 1",
        img: "",
        value: 600,
    },
    {
        figName: "Short Cut",
        characterId: 101,
        elementId: 7,
        gameId: 4,
        type: "master",
        variation: "series 1",
        img: "",
        value: 1000,
    },
    {
        figName: "Snap Shot",
        characterId: 102,
        elementId: 2,
        gameId: 4,
        type: "master",
        variation: "series 1",
        img: "",
        value: 200,
    },
    {
        figName: "Thunderbolt",
        characterId: 103,
        elementId: 5,
        gameId: 4,
        type: "master",
        variation: "series 1",
        img: "",
        value: 250,
    },
    {
        figName: "Tuff Luck",
        characterId: 104,
        elementId: 8,
        gameId: 4,
        type: "master",
        variation: "series 1",
        img: "",
        value: 600,
    },
    {
        figName: "Wallop",
        characterId: 105,
        elementId: 4,
        gameId: 4,
        type: "master",
        variation: "series 1",
        img: "",
        value: 1000,
    },
    {
        figName: "Wildfire",
        characterId: 106,
        elementId: 1,
        gameId: 4,
        type: "master",
        variation: "series 1",
        img: "",
        value: 1000,
    },
    // traps
    {
        figName: "Tempest Timer",
        characterId: 107,
        elementId: 5,
        gameId: 4,
        type: "trap",
        variation: "hourglass",
        img: "",
        value: 600,
    },
    {
        figName: "Drafty Decanter",
        characterId: 107,
        elementId: 5,
        gameId: 4,
        type: "trap",
        variation: "jughead",
        img: "",
        value: 600,
    },
    {
        figName: "Storm Warning",
        characterId: 107,
        elementId: 5,
        gameId: 4,
        type: "trap",
        variation: "screamer",
        img: "",
        value: 600,
    },
    {
        figName: "Cloudy Cobra",
        characterId: 107,
        elementId: 5,
        gameId: 4,
        type: "trap",
        variation: "snake",
        img: "",
        value: 600,
    },
    {
        figName: "Cyclone Sabre",
        characterId: 107,
        elementId: 5,
        gameId: 4,
        type: "trap",
        variation: "sword",
        img: "",
        value: 600,
    },
    {
        figName: "Breezy Bird",
        characterId: 107,
        elementId: 5,
        gameId: 4,
        type: "trap",
        variation: "toucan",
        img: "",
        value: 600,
    },
    {
        figName: "Ghastly Grimace",
        characterId: 108,
        elementId: 10,
        gameId: 4,
        type: "trap",
        variation: "handstand",
        img: "",
        value: 2500,
    },
    {
        figName: "Shadow Spider",
        characterId: 108,
        elementId: 10,
        gameId: 4,
        setId: 13,
        type: "trap",
        variation: "spider",
        img: "",
        value: 2500,
    },
    {
        figName: "Dark Dagger",
        characterId: 108,
        elementId: 10,
        gameId: 4,
        type: "trap",
        variation: "sword",
        img: "",
        value: 2500,
    },
    {
        figName: "Slag Hammer",
        characterId: 109,
        elementId: 4,
        gameId: 4,
        type: "trap",
        variation: "hammer",
        img: "",
        value: 400,
    },
    {
        figName: "Rubble Trouble",
        characterId: 109,
        elementId: 4,
        gameId: 4,
        type: "trap",
        variation: "handstand",
        img: "",
        value: 400,
    },
    {
        figName: "Dust of Time",
        characterId: 109,
        elementId: 4,
        gameId: 4,
        type: "trap",
        variation: "hourglass",
        img: "",
        value: 400,
    },
    {
        figName: "Banded Boulder",
        characterId: 109,
        elementId: 4,
        gameId: 4,
        type: "trap",
        variation: "orb",
        img: "",
        value: 400,
    },
    {
        figName: "Spinning Sandstorm",
        characterId: 109,
        elementId: 4,
        gameId: 4,
        type: "trap",
        variation: "totem",
        img: "",
        value: 400,
    },
    {
        figName: "Rock Hawk",
        characterId: 109,
        elementId: 4,
        gameId: 4,
        type: "trap",
        variation: "toucan",
        img: "",
        value: 400,
    },
    {
        figName: "Spark Spear",
        characterId: 110,
        elementId: 1,
        gameId: 4,
        type: "trap",
        variation: "hat",
        img: "",
        value: 600,
    },
    {
        figName: "Fire Flower",
        characterId: 110,
        elementId: 1,
        gameId: 4,
        type: "trap",
        variation: "scepter",
        img: "",
        value: 600,
    },
    {
        figName: "Scorching Stopper",
        characterId: 110,
        elementId: 1,
        gameId: 4,
        type: "trap",
        variation: "screamer",
        img: "",
        value: 600,
    },
    {
        figName: "Eternal Flame",
        characterId: 110,
        elementId: 1,
        gameId: 4,
        type: "trap",
        variation: "torch",
        img: "",
        value: 600,
    },
    {
        figName: "Searing Spinner",
        characterId: 110,
        elementId: 1,
        gameId: 4,
        type: "trap",
        variation: "totem",
        img: "",
        value: 600,
    },
    {
        figName: "Blazing Belch",
        characterId: 110,
        elementId: 1,
        gameId: 4,
        type: "trap",
        variation: "yawn",
        img: "",
        rare: true,
        value: 13000,
    },
    {
        figName: "Kaos Trap",
        characterId: 111,
        elementId: 10,
        gameId: 4,
        type: "trap",
        variation: "kaos",
        img: "",
        value: 1400,
    },
    {
        figName: "Weed Whacker",
        characterId: 112,
        elementId: 8,
        gameId: 4,
        type: "trap",
        variation: "hammer",
        img: "",
        value: 300,
    },
    {
        figName: "Seed Serpent",
        characterId: 112,
        elementId: 8,
        gameId: 4,
        type: "trap",
        variation: "snake",
        img: "",
        value: 300,
    },
    {
        figName: "Jade Blade",
        characterId: 112,
        elementId: 8,
        gameId: 4,
        type: "trap",
        variation: "sword",
        img: "",
        value: 300,
    },
    {
        figName: "Emerald Energy",
        characterId: 112,
        elementId: 8,
        gameId: 4,
        type: "trap",
        variation: "torch",
        img: "",
        value: 300,
    },
    {
        figName: "Oak Eagle",
        characterId: 112,
        elementId: 8,
        gameId: 4,
        type: "trap",
        variation: "toucan",
        img: "",
        value: 300,
    },
    {
        figName: "Shrub Shrieker",
        characterId: 112,
        elementId: 8,
        gameId: 4,
        type: "trap",
        variation: "yawn",
        img: "",
        rare: true,
        value: 22500,
    },
    {
        figName: "Heavenly Hawk",
        characterId: 113,
        elementId: 9,
        gameId: 4,
        setId: 14,
        type: "trap",
        variation: "owl",
        img: "",
        rare: true,
        value: 3000,
    },
    {
        figName: "Shining Ship",
        characterId: 113,
        elementId: 9,
        gameId: 4,
        type: "trap",
        variation: "rocket",
        img: "",
        rare: true,
        value: 3000,
    },
    {
        figName: "Beam Scream",
        characterId: 113,
        elementId: 9,
        gameId: 4,
        type: "trap",
        variation: "yawn",
        img: "",
        rare: true,
        value: 10000,
    },
    {
        figName: "Axe of Illusion",
        characterId: 114,
        elementId: 6,
        gameId: 4,
        type: "trap",
        variation: "axe",
        img: "",
        value: 700,
    },
    {
        figName: "Arcane Hourglass",
        characterId: 114,
        elementId: 6,
        gameId: 4,
        type: "trap",
        variation: "hourglass",
        img: "",
        value: 700,
    },
    {
        figName: "Biter's Bane",
        characterId: 114,
        elementId: 6,
        gameId: 4,
        type: "trap",
        variation: "log",
        img: "",
        value: 700,
    },
    {
        figName: "Rune Rocket",
        characterId: 114,
        elementId: 6,
        gameId: 4,
        type: "trap",
        variation: "rocket",
        img: "",
        value: 700,
    },
    {
        figName: "Sorcerous Skull",
        characterId: 114,
        elementId: 6,
        gameId: 4,
        type: "trap",
        variation: "skull",
        img: "",
        value: 700,
    },
    {
        figName: "Spell Slapper",
        characterId: 114,
        elementId: 6,
        gameId: 4,
        type: "trap",
        variation: "totem",
        img: "",
        value: 700,
    },
    {
        figName: "Automatic Angel",
        characterId: 115,
        elementId: 3,
        gameId: 4,
        type: "trap",
        variation: "angel",
        img: "",
        value: 1000,
    },
    {
        figName: "Makers Mana",
        characterId: 115,
        elementId: 3,
        gameId: 4,
        type: "trap",
        variation: "helmet",
        img: "",
        value: 1000,
    },
    {
        figName: "Grabbing Gadget",
        characterId: 115,
        elementId: 3,
        gameId: 4,
        type: "trap",
        variation: "hand",
        img: "",
        value: 1000,
    },
    {
        figName: "Topsy Techy",
        characterId: 115,
        elementId: 3,
        gameId: 4,
        type: "trap",
        variation: "handstand",
        img: "",
        value: 1000,
    },
    {
        figName: "Factory Flower",
        characterId: 115,
        elementId: 3,
        gameId: 4,
        type: "trap",
        variation: "scepter",
        img: "",
        value: 1000,
    },
    {
        figName: "Tech Totem",
        characterId: 115,
        elementId: 3,
        gameId: 4,
        type: "trap",
        variation: "tiki",
        img: "",
        value: 1000,
    },
    {
        figName: "Haunted Hatchet",
        characterId: 116,
        elementId: 7,
        gameId: 4,
        type: "trap",
        variation: "axe",
        img: "",
        value: 900,
    },
    {
        figName: "Dream Piercer",
        characterId: 116,
        elementId: 7,
        gameId: 4,
        type: "trap",
        variation: "hat",
        img: "",
        value: 900,
    },
    {
        figName: "Grim Gripper",
        characterId: 116,
        elementId: 7,
        gameId: 4,
        type: "trap",
        variation: "hand",
        img: "",
        value: 900,
    },
    {
        figName: "Spirit Sphere",
        characterId: 116,
        elementId: 7,
        gameId: 4,
        type: "trap",
        variation: "orb",
        img: "",
        value: 900,
    },
    {
        figName: "Spectral Skull",
        characterId: 116,
        elementId: 7,
        gameId: 4,
        type: "trap",
        variation: "skull",
        img: "",
        value: 900,
    },
    {
        figName: "Spooky Snake",
        characterId: 116,
        elementId: 7,
        gameId: 4,
        type: "trap",
        variation: "snake",
        img: "",
        value: 900,
    },
    {
        figName: "Soaking Staff",
        characterId: 117,
        elementId: 2,
        gameId: 4,
        type: "trap",
        variation: "angel",
        img: "",
        value: 200,
    },
    {
        figName: "Aqua Axe",
        characterId: 117,
        elementId: 2,
        gameId: 4,
        type: "trap",
        variation: "axe",
        img: "",
        value: 200,
    },
    {
        figName: "Frost Helm",
        characterId: 117,
        elementId: 2,
        gameId: 4,
        type: "trap",
        variation: "helmet",
        img: "",
        value: 200,
    },
    {
        figName: "Flood Flask",
        characterId: 117,
        elementId: 2,
        gameId: 4,
        type: "trap",
        variation: "jughead",
        img: "",
        value: 200,
    },
    {
        figName: "Wet Walter",
        characterId: 117,
        elementId: 2,
        gameId: 4,
        type: "trap",
        variation: "log",
        img: "",
        value: 200,
    },
    {
        figName: "Tidal Tiki",
        characterId: 117,
        elementId: 2,
        gameId: 4,
        type: "trap",
        variation: "tiki",
        img: "",
        value: 200,
    },
    // standard figures
    {
        figName: "Bat Spin",
        characterId: 118,
        elementId: 7,
        gameId: 4,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: true,
        value: 1500,
    },
    {
        figName: "Blackout",
        characterId: 119,
        elementId: 10,
        gameId: 4,
        type: "standard",
        variation: "series 1",
        img: "",
        rare: true,
        value: 3500,
    },
    {
        figName: "Blades",
        characterId: 120,
        elementId: 10,
        gameId: 4,
        setId: 11,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 400,
    },
    {
        figName: "Chopper",
        characterId: 121,
        elementId: 3,
        gameId: 4,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 400,
    },
    {
        figName: "Cobra Cadabra",
        characterId: 122,
        elementId: 6,
        gameId: 4,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 800,
    },
    {
        figName: "Deja Vu",
        characterId: 123,
        elementId: 6,
        gameId: 4,
        setId: 12,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 200,
    },
    {
        figName: "Echo",
        characterId: 124,
        elementId: 2,
        gameId: 4,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 2000,
    },
    {
        figName: "Fist Bump",
        characterId: 125,
        elementId: 4,
        gameId: 4,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 300,
    },
    {
        figName: "Fling Kong",
        characterId: 126,
        elementId: 5,
        gameId: 4,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 1300,
    },
    {
        figName: "Flip Wreck",
        characterId: 127,
        elementId: 2,
        gameId: 4,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 1400,
    },
    {
        figName: "Food Fight",
        characterId: 128,
        elementId: 8,
        gameId: 4,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 200,
    },
    {
        figName: "Hog Wild Fryno",
        characterId: 76,
        elementId: 1,
        gameId: 4,
        type: "standard",
        variation: "series 2",
        img: "",
        value: 150,
    },
    {
        figName: "Funny Bone",
        characterId: 129,
        elementId: 7,
        gameId: 4,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 250,
    },
    {
        figName: "Tidal Wave Gill Grunt",
        characterId: 13,
        elementId: 2,
        gameId: 4,
        type: "standard",
        variation: "series 4",
        img: "",
        value: 050,
    },
    {
        figName: "High Five",
        characterId: 130,
        elementId: 8,
        gameId: 4,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 1000,
    },
    {
        figName: "Full Blast Jet Vac",
        characterId: 46,
        elementId: 5,
        gameId: 4,
        type: "standard",
        variation: "series 3",
        img: "",
        value: 050,
    },
    {
        figName: "Fizzy Frenzy Pop Fizz",
        characterId: 47,
        elementId: 6,
        gameId: 4,
        type: "standard",
        variation: "series 3",
        img: "",
        value: 150,
    },
    {
        figName: "Rocky Roll",
        characterId: 131,
        elementId: 4,
        gameId: 4,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 2000,
    },
    {
        figName: "Sure Shot Shroomboom",
        characterId: 45,
        elementId: 8,
        gameId: 4,
        type: "standard",
        variation: "series 2",
        img: "",
        value: 050,
    },
    {
        figName: "Spotlight",
        characterId: 132,
        elementId: 9,
        gameId: 4,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 3500,
    },
    {
        figName: "Torch",
        characterId: 133,
        elementId: 1,
        gameId: 4,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 250,
    },
    {
        figName: "Trail Blazer",
        characterId: 134,
        elementId: 1,
        gameId: 4,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 1000,
    },
    {
        figName: "Tread Head",
        characterId: 135,
        elementId: 3,
        gameId: 4,
        type: "standard",
        variation: "series 1",
        img: "",
        value: 500,
    },
    // sidekicks
    {
        figName: "Barkley S-2",
        characterId: 53,
        elementId: 8,
        gameId: 4,
        type: "sidekick",
        variation: "series 2",
        img: "",
        value: 1000,
    },
    {
        figName: "Bop",
        characterId: 136,
        elementId: 4,
        gameId: 4,
        type: "sidekick",
        variation: "series 1",
        img: "",
        value: 400,
    },
    {
        figName: "Breeze",
        characterId: 137,
        elementId: 5,
        gameId: 4,
        type: "sidekick",
        variation: "series 1",
        img: "",
        rare: true,
        value: 7000,
    },
    {
        figName: "Drobit",
        characterId: 138,
        elementId: 3,
        gameId: 4,
        type: "sidekick",
        variation: "series 1",
        img: "",
        value: 300,
    },
    {
        figName: "Eye Small S-2",
        characterId: 54,
        elementId: 7,
        gameId: 4,
        type: "sidekick",
        variation: "series 2",
        img: "",
        value: 500,
    },
    {
        figName: "Gill Runt S-2",
        characterId: 33,
        elementId: 2,
        gameId: 4,
        type: "sidekick",
        variation: "series 2",
        img: "",
        value: 400,
    },
    {
        figName: "Hijinx",
        characterId: 139,
        elementId: 7,
        gameId: 4,
        type: "sidekick",
        variation: "series 1",
        img: "",
        value: 050,
    },
    {
        figName: "Mini Jini",
        characterId: 55,
        elementId: 6,
        gameId: 4,
        type: "sidekick",
        variation: "series 1",
        img: "",
        value: 300,
    },
    {
        figName: "Pet Vac",
        characterId: 140,
        elementId: 5,
        gameId: 4,
        type: "sidekick",
        variation: "series 1",
        img: "",
        value: 1000,
    },
    {
        figName: "Small Fry",
        characterId: 141,
        elementId: 1,
        gameId: 4,
        type: "sidekick",
        variation: "series 1",
        img: "",
        value: 400,
    },
    {
        figName: "Spry",
        characterId: 142,
        elementId: 6,
        gameId: 4,
        type: "sidekick",
        variation: "series 1",
        img: "",
        value: 200,
    },
    {
        figName: "Terrabite S-2",
        characterId: 34,
        elementId: 4,
        gameId: 4,
        type: "sidekick",
        variation: "series 2",
        img: "",
        value: 250,
    },
    {
        figName: "Thumpling S-2",
        characterId: 56,
        elementId: 2,
        gameId: 4,
        type: "sidekick",
        variation: "series 2",
        img: "",
        value: 700,
    },
    {
        figName: "Trigger Snappy S-2",
        characterId: 35,
        elementId: 3,
        gameId: 4,
        type: "sidekick",
        variation: "series 2",
        img: "",
        value: 400,
    },
    {
        figName: "Weeruptor",
        characterId: 143,
        elementId: 1,
        gameId: 4,
        type: "sidekick",
        variation: "series 1",
        img: "",
        value: 1000,
    },
    {
        figName: "Whisper Elf S-2",
        characterId: 36,
        elementId: 8,
        gameId: 4,
        type: "sidekick",
        variation: "series 2",
        img: "",
        value: 1500,
    },
    // variants
    {
        figName: "Dark Food Fight",
        characterId: 128,
        elementId: 8,
        gameId: 4,
        type: "standard",
        variation: "dark",
        img: "",
        value: 150,
    },
    {
        figName: "Dark Snap Shot",
        characterId: 102,
        elementId: 2,
        gameId: 4,
        type: "master",
        variation: "dark",
        img: "",
        value: 300,
    },
    {
        figName: "Dark Wildfire",
        characterId: 106,
        elementId: 1,
        gameId: 4,
        type: "master",
        variation: "dark",
        img: "",
        value: 700,
    },
    {
        figName: "Eggsellent Weeruptor",
        characterId: 143,
        elementId: 1,
        gameId: 4,
        type: "sidekick",
        variation: "holiday",
        img: "",
        rare: true,
        value: 1000,
    },
    {
        figName: "Gnarly Barkley",
        characterId: 53,
        elementId: 8,
        gameId: 4,
        type: "sidekick",
        variation: "gnarly",
        img: "",
        rare: true,
        value: 1400,
    },
    {
        figName: "King Cobra Cadabra",
        characterId: 122,
        elementId: 6,
        gameId: 4,
        type: "standard",
        variation: "king",
        img: "",
        rare: true,
        value: 1000,
    },
    {
        figName: "Legendary Blades",
        characterId: 120,
        elementId: 10,
        gameId: 4,
        setId: 11,
        type: "standard",
        variation: "legendary",
        img: "",
        value: 300,
    },
    {
        figName: "Legendary Bushwhack",
        characterId: 90,
        elementId: 8,
        gameId: 4,
        type: "master",
        variation: "legendary",
        img: "",
        value: 800,
    },
    {
        figName: "Legendary Deja Vu",
        characterId: 123,
        elementId: 6,
        gameId: 4,
        type: "standard",
        variation: "legendary",
        img: "",
        value: 300,
    },
    {
        figName: "Legendary Jawbreaker",
        characterId: 95,
        elementId: 3,
        gameId: 4,
        type: "master",
        variation: "legendary",
        img: "",
        value: 800,
    },
    {
        figName: "Love Potion Pop Fizz",
        characterId: 47,
        elementId: 6,
        gameId: 4,
        type: "standard",
        variation: "holiday",
        img: "",
        value: 600,
    },
    {
        figName: "Nitro Head Rush",
        characterId: 94,
        elementId: 4,
        gameId: 4,
        type: "master",
        variation: "nitro",
        img: "",
        value: 800,
    },
    {
        figName: "Nitro Krypt King",
        characterId: 99,
        elementId: 7,
        gameId: 4,
        type: "master",
        variation: "nitro",
        img: "",
        value: 800,
    },
    {
        figName: "Power Punch Pet Vac",
        characterId: 140,
        elementId: 5,
        gameId: 4,
        type: "sidekick",
        variation: "red",
        img: "",
        value: 1000,
    },
    {
        figName: "Winterfest Lob-Star",
        characterId: 100,
        elementId: 2,
        gameId: 4,
        type: "master",
        variation: "holiday",
        img: "",
        value: 800,
    },
    {
        figName: "Clear Short Cut",
        characterId: 101,
        elementId: 7,
        gameId: 4,
        type: "master",
        variation: "clear",
        img: "",
        rare: true,
        value: 17500,
    },
    {
        figName: "Clear Thunderbolt",
        characterId: 103,
        elementId: 5,
        gameId: 4,
        type: "master",
        variation: "clear",
        img: "",
        rare: true,
        value: 12500,
    },
    {
        figName: "Clear Tuff Luck",
        characterId: 104,
        elementId: 8,
        gameId: 4,
        type: "master",
        variation: "clear",
        img: "",
        rare: true,
        value: 15000,
    },
    {
        figName: "Easter Bunny Rubble Trouble",
        characterId: 109,
        elementId: 4,
        gameId: 4,
        type: "trap",
        variation: "holiday",
        img: "",
        rare: true,
        value: 1000,
    },
    {
        figName: "Legendary Spirit Sphere",
        characterId: 116,
        elementId: 7,
        gameId: 4,
        type: "trap",
        variation: "legendary",
        img: "",
        rare: true,
        value: 1000,
    },
    {
        figName: "Legendary Spectral Skull",
        characterId: 116,
        elementId: 7,
        gameId: 4,
        type: "trap",
        variation: "legendary",
        img: "legendary",
        rare: true,
        value: 1000,
    },
    {
        figName: "Legendary Flood Flask",
        characterId: 117,
        elementId: 2,
        gameId: 4,
        type: "trap",
        variation: "legendary",
        img: "",
        rare: true,
        value: 1000,
    },
    {
        figName: "Ultimate Kaos Trap",
        characterId: 111,
        elementId: 10,
        gameId: 4,
        type: "trap",
        variation: "ultimate",
        img: "",
        rare: true,
        value: 2000,
    },
    {
        figName: "Red Hot Tussle Sprout",
        characterId: 109,
        elementId: 4,
        gameId: 4,
        type: "trap",
        variation: "totem",
        img: "",
        rare: true,
        value: 2000,
    },
    {
        figName: "Rebel Lob Goblin",
        characterId: 113,
        elementId: 9,
        gameId: 4,
        type: "trap",
        variation: "rocket",
        img: "",
        rare: true,
        value: 3500,
    },
    {
        figName: "Outlaw Brawl and Chain",
        characterId: 117,
        elementId: 2,
        gameId: 4,
        type: "trap",
        variation: "log",
        img: "",
        rare: true,
        value: 700,
    },
    {
        figName: "Riot Shield Shredder",
        characterId: 112,
        elementId: 8,
        gameId: 4,
        type: "trap",
        variation: "torch",
        img: "",
        rare: true,
        value: 2000,
    },
    {
        figName: "Steamed Broccoli Guy",
        characterId: 112,
        elementId: 8,
        gameId: 4,
        type: "trap",
        variation: "toucan",
        img: "",
        rare: true,
        value: 1000,
    },
    {
        figName: "Steampunk Shrednaught",
        characterId: 115,
        elementId: 3,
        gameId: 4,
        type: "trap",
        variation: "helmet",
        img: "",
        rare: true,
        value: 2000,
    },
    // Eon's Elite Trap Team
    {
        figName: "Elite Chop Chop",
        characterId: 4,
        elementId: 7,
        gameId: 4,
        type: "standard",
        variation: "elite",
        img: "",
        rare: true,
        value: 1500,
    },
    {
        figName: "Elite Eruptor",
        characterId: 10,
        elementId: 1,
        gameId: 4,
        type: "standard",
        variation: "elite",
        img: "",
        rare: true,
        value: 1500,
    },
    {
        figName: "Elite Gill Grunt",
        characterId: 13,
        elementId: 2,
        gameId: 4,
        type: "standard",
        variation: "elite",
        img: "",
        rare: true,
        value: 1500,
    },
    {
        figName: "Elite Spyro",
        characterId: 20,
        elementId: 6,
        gameId: 4,
        type: "standard",
        variation: "elite",
        img: "",
        rare: true,
        value: 1000,
    },
    {
        figName: "Elite Stealth Elf",
        characterId: 21,
        elementId: 8,
        gameId: 4,
        type: "standard",
        variation: "elite",
        img: "",
        rare: true,
        value: 2000,
    },
    {
        figName: "Elite Terrafin",
        characterId: 24,
        elementId: 4,
        gameId: 4,
        type: "standard",
        variation: "elite",
        img: "",
        rare: true,
        value: 1000,
    },
    {
        figName: "Elite Trigger Happy",
        characterId: 24,
        elementId: 4,
        gameId: 4,
        type: "standard",
        variation: "elite",
        img: "",
        rare: true,
        value: 1000,
    },
    {
        figName: "Elite Whirlwind",
        characterId: 24,
        elementId: 4,
        gameId: 4,
        type: "standard",
        variation: "elite",
        img: "",
        rare: true,
        value: 1000,
    },
];

module.exports = trapFigures;