import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
// import prisma from '../db';
import Header from '../components/Header';
import AllFigureList from '../components/AllFigureList';
import AllAccessoriesList from '../components/AllAccessoriesList';

import { ApolloProvider } from '@apollo/client';
import { useState } from 'react';

export default function Home({}) {
  const [showFigures, setShowFigures] = useState(true);
  const [showAcc, setShowAcc] = useState(false);
  return (
    <div className={styles.container}>
      <Head>
        <title>Katy's Toybox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Luckiest+Guy&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Header setShowFigures={setShowFigures} setShowAcc={setShowAcc}></Header>

      <main className={styles.main}>
        <div>
          {showFigures && <AllFigureList></AllFigureList>}
          {showAcc && <AllAccessoriesList></AllAccessoriesList>}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

// export async function getServerSideProps() {
//   const { data } = await client.query({
//     query: gql`
//       query Countries {
//         countries {
//           code
//           name
//           emoji
//         }
//       }
//     `,
//   });

//   return {
//     props: {
//       countries: data.countries.slice(0, 4),
//     },
//   };
// }
